module.exports = ({ kw }) => ({
  frame_phrase: ($) =>
    seq(
      prec(1, kw("WITH")),
      repeat1(
        choice(
          $.at_phrase,
          $.size_phrase,
          alias(kw("NO-LABELS"), $.no_labels),
          alias(kw("NO-LABEL"), $.no_label),
          alias(kw("SIDE-LABELS", { offset: 10 }), $.side_labels),
          alias(kw("CENTERED", { offset: 6 }), $.centered),
          alias(kw("THREE-D"), $.three_d),
          alias(kw("NO-BOX"), $.no_box),
          alias(kw("ATTR-SPACE"), $.attr_space),
          alias(kw("NO-ATTR-SPACE"), $.no_attr_space),
          alias(kw("OVERLAY"), $.overlay),
          alias(kw("PAGE-TOP"), $.page_top),
          alias(kw("PAGE-BOTTOM"), $.page_bottom),
          alias(kw("USE-TEXT"), $.use_text),
          alias(kw("BACKGROUND"), $.background),
          alias(kw("NO-HIDE"), $.no_hide),
          alias(kw("NO-UNDERLINE", { offset: 10 }), $.no_underline),
          alias(kw("NO-HELP"), $.no_help),
          alias(kw("SCROLLABLE"), $.scrollable),
          alias(kw("TOP-ONLY"), $.top_only),
          alias(kw("SCREEN-IO"), $.screen_io),
          alias(kw("KEEP-TAB-ORDER"), $.keep_tab_order),
          alias(kw("DROP-TARGET"), $.drop_target),
          alias(kw("CONTEXT-HELP"), $.context_help),
          alias(kw("EXPORT"), $.export),
          alias(kw("USE-DICT-EXPS"), $.use_dict_exps),
          alias(kw("ACCUM"), $.accum),
          seq(kw("FRAME"), field("frame", $.__frame_identifier), optional(kw("WITH"))),
          seq(kw("BROWSE"), field("browse", $.__frame_identifier), optional(kw("WITH"))),
          seq(kw("ROW"), field("row", $.__frame_expression)),
          seq(kw("WIDTH"), field("width", $.__frame_expression)),
          seq(kw("FONT"), field("font", $.number_literal)),
          seq(kw("CANCEL-BUTTON"), field("cancel_button", $.__frame_identifier)),
          seq(kw("DEFAULT-BUTTON"), field("default_button", $.__frame_identifier)),
          seq(kw("SCROLL"), field("scroll", $.__frame_expression)),
          seq(kw("RETAIN"), field("retain", $.__frame_expression)),
          seq(kw("WIDGET-ID"), field("widget_id", $.__frame_expression)),
          seq(kw("CONTEXT-HELP-FILE"), field("context_help_file", $.__frame_expression)),
          seq(kw("IN"), kw("WINDOW"), field("window", $.__frame_identifier)),
          seq(kw("BGCOLOR"), field("bgcolor", $.__frame_expression)),
          seq(kw("DCOLOR"), field("dcolor", $.__frame_expression)),
          seq(kw("FGCOLOR"), field("fgcolor", $.__frame_expression)),
          seq(kw("PFCOLOR"), field("pfcolor", $.__frame_expression)),
          $.__frame_title_phrase,
          choice(
            seq(field("column", $.number_literal), choice(kw("COLUMN"), kw("COLUMNS"), kw("COL"))),
            seq(
              choice(kw("COLUMN"), kw("COLUMNS"), kw("COL")),
              field("column", $.__frame_expression),
            ),
          ),
          alias(seq(kw("VIEW-AS"), field("widget", kw("DIALOG-BOX"))), $.view_as_phrase),
          alias($.__frame_down_count, $.down),
          alias($.__frame_down_value, $.down),
          alias($.__frame_down_plain, $.down),
          $.__frame_skip_phrase,
        ),
      ),
    ),

  __frame_skip_phrase: ($) =>
    prec.left(seq(kw("SKIP"), optional(field("skip", seq("(", $.__frame_expression, ")"))))),

  __frame_title_phrase: ($) =>
    seq(
      kw("TITLE"),
      optional(
        choice(
          seq(kw("BGCOLOR"), field("title_bgcolor", $.__frame_expression)),
          seq(kw("DCOLOR"), field("title_dcolor", $.__frame_expression)),
          seq(kw("FGCOLOR"), field("title_fgcolor", $.__frame_expression)),
          seq(kw("FONT"), field("title_font", $.__frame_expression)),
        ),
      ),
      field("title", $.__frame_expression),
    ),
  __frame_identifier: ($) => $.identifier,
  __frame_expression: ($) => $._expression,
  __frame_down_value: ($) => seq(field("value", $.__frame_expression), kw("DOWN")),
  __frame_down_count: ($) =>
    prec.right(1, seq(kw("DOWN"), field("count", $.__frame_down_expression))),
  __frame_down_plain: ($) => prec(-1, seq(kw("DOWN"))),
  __frame_down_expression: ($) => choice($.number_literal, $.parenthesized_expression),
});
