module.exports = ({ kw, tkw }) => ({
  frame_phrase: ($) =>
    seq(
      kw("WITH"),
      repeat(
        choice(
          seq(kw("FRAME"), field("frame", $.identifier)),
          seq(kw("BROWSE"), field("browse", $.identifier)),
          seq(
            choice(tkw("SIZE"), tkw("SIZE-CHARS"), tkw("SIZE-PIXELS")),
            $._expression,
            kw("BY"),
            $._expression,
          ),
          alias($.__frame_option_no_labels, $.frame_option),
          alias($.__frame_option_side_labels, $.frame_option),
          alias($.__frame_option_centered, $.frame_option),
          alias($.__frame_option_no_box, $.frame_option),
          alias($.__frame_option_overlay, $.frame_option),
          alias($.__frame_option_page_top, $.frame_option),
          alias($.__frame_option_page_bottom, $.frame_option),
          alias($.__frame_option_use_text, $.frame_option),
          alias($.__frame_option_down, $.frame_option),
          alias($.__frame_option_column_count, $.frame_option),
          alias($.__frame_option_columns_count, $.frame_option),
          alias($.__frame_option_title, $.frame_option),
          alias($.__frame_option_row, $.frame_option),
          alias($.__frame_option_column, $.frame_option),
          alias($.__frame_option_width, $.frame_option),
          alias($.__frame_option_view_as, $.frame_option),
        ),
      ),
    ),
  __frame_option_no_labels: ($) => tkw("NO-LABELS"),
  __frame_option_side_labels: ($) => tkw("SIDE-LABELS"),
  __frame_option_centered: ($) => tkw("CENTERED"),
  __frame_option_no_box: ($) => tkw("NO-BOX"),
  __frame_option_overlay: ($) => tkw("OVERLAY"),
  __frame_option_page_top: ($) => tkw("PAGE-TOP"),
  __frame_option_page_bottom: ($) => tkw("PAGE-BOTTOM"),
  __frame_option_use_text: ($) => tkw("USE-TEXT"),
  __frame_option_down: ($) =>
    choice(
      prec(1, seq($._expression, tkw("DOWN"))),
      seq(tkw("DOWN"), $._expression),
      tkw("DOWN"),
    ),
  __frame_option_column_count: ($) => seq($.number_literal, tkw("COLUMN")),
  __frame_option_columns_count: ($) => seq($.number_literal, tkw("COLUMNS")),
  __frame_option_title: ($) => seq(kw("TITLE"), field("title", $._expression)),
  __frame_option_row: ($) => seq(kw("ROW"), field("row", $._expression)),
  __frame_option_column: ($) => seq(kw("COLUMN"), field("column", $._expression)),
  __frame_option_width: ($) => seq(kw("WIDTH"), field("width", $._expression)),
  __frame_option_view_as: ($) => seq(kw("VIEW-AS"), tkw("DIALOG-BOX")),
});
