// References: N/A (barrel for precedence groups).
// Purpose: compose all precedence groups in a stable, readable order.

module.exports = ($) => [
  ["unary", "multiplication", "add", "compare", "not", "logical"],
  ...require("./binary")($),
  ...require("./os")($),
  ...require("./dataset")($),
  ...require("./browse")($),
  ...require("./include")($),
  ...require("./create")($),
  ...require("./delete")($),
  ...require("./case")($),
  ...require("./assign")($),
  ...require("./set")($),
  ...require("./enable")($),
  ...require("./display")($),
  ...require("./widget")($),
  ...require("./message")($),
  ...require("./record")($),
  ...require("./frame")($),
  ...require("./format")($),
  ...require("./put")($),
  ...require("./prompt-for")($),
  ...require("./export")($),
  ...require("./input")($),
  ...require("./run")($),
  ...require("./subscribe")($),
  ...require("./update")($),
];
