(comment) @comment
(line_comment) @comment
(block_comment) @comment
(global_define_preprocessor_directive) @preproc
(scoped_define_preprocessor_directive) @preproc
(if_preprocessor_directive) @preproc
(message_preprocessor_directive) @preproc
(undefine_preprocessor_directive) @preproc
(if_branch) @preproc
(then_branch) @preproc
(elseif_branch) @preproc
(else_branch) @preproc
(endif_branch) @preproc
(global_define_preprocessor_directive name: (identifier) @constant)
(scoped_define_preprocessor_directive name: (identifier) @constant)
(undefine_preprocessor_directive name: (identifier) @constant)
(preprocessor_value) @string.special
(preprocessor_name) @macro
(include_file_reference) @include
(include_file_reference) @preproc
(include_file_path (identifier) @string)
(include_argument name: (identifier) @attribute)
(include_argument name: (identifier) @parameter)
(constant) @constant
(constant) @constant.builtin
(constant) @macro
(argument_reference) @constant
(argument_reference) @constant.builtin
(null_literal) @constant
(boolean_literal) @boolean
(boolean_literal) @constant.builtin
((identifier) @boolean (#match? @boolean "^(?i:true|false|yes|no)$"))
(number_literal) @number
(date_literal) @number
(string_literal) @string
(identifier) @variable

(scope_modifier) @keyword
(serialization_modifier) @keyword
(no_lock) @keyword

(function_definition name: (identifier) @function.definition)
(function_forward_definition name: (identifier) @function.definition)
(procedure_definition name: (identifier) @function.definition)
(function_call function: (identifier) @function.call)
(function_call function: (qualified_name) @function.call)
(function_call function: (object_access) @function.call)
(function_call function: (scoped_name) @function.call)
(run_statement procedure: (procedure_name) @function.call)
(run_statement procedure: (identifier) @function.call)
(run_statement procedure: (qualified_name) @function.call)
(parameter name: (identifier) @parameter)
(parameter_definition name: (identifier) @parameter)
(buffer_definition name: (identifier) @variable.definition)
(stream_definition name: (identifier) @variable.definition)
(query_definition name: (identifier) @variable.definition)
(image_definition name: (identifier) @variable.definition)
(temp_table_definition name: (identifier) @type)
(work_table_definition name: (identifier) @type)
(temp_table_field name: (identifier) @property)
(temp_table_index name: (identifier) @property)
(_ type: (_) @type)
(no_undo) @keyword
(no_error) @keyword
(assignment_operator) @operator

(access_modifier) @keyword
(static_modifier) @keyword
(scope_modifier) @keyword
(serialization_modifier) @keyword

[
  "AND"
  "BEGINS"
  "EQ"
  "GE"
  "GT"
  "LE"
  "LT"
  "MATCHES"
  "MOD"
  "NE"
  "NOT"
  "OR"
] @operator

[
  "<"
  "<="
  "<>"
  "="
  ">"
  ">="
  "+"
  "-"
  "*"
  "/"
] @operator

[
  (abstract)
  (abstract_modifier)
  (access_modifier)
  (all)
  (allow_replication)
  (ansi_only)
  (anywhere)
  (append)
  (array_message)
  (ask_overwrite)
  (attr_space)
  (auto_endkey)
  (auto_go)
  (auto_return)
  (background)
  (backwards)
  (before_hide)
  (binary)
  (bind)
  (bind_where)
  (blank)
  (break)
  (byte)
  (by_reference)
  (by_value)
  (case_sensitive)
  (cdecl)
  (centered)
  (chained)
  (clear)
  (clipboard)
  (close)
  (collate)
  (compares)
  (convert_3d_colors)
  (create_test_file)
  (current)
  (cursor)
  (data_bind)
  (deblank)
  (default)
  (disabled)
  (disable_auto_zap)
  (display)
  (down)
  (drop_down)
  (drop_down_list)
  (drop_target)
  (echo)
  (exclusive)
  (exclusive_lock)
  (explicit)
  (final)
  (final_modifier)
  (first)
  (fit_last_column)
  (fixed_only)
  (flags)
  (flat_button)
  (foreign_key_hidden)
  (forward)
  (forwards)
  (from_current)
  (generate_md5)
  (graphic_edge)
  (group_box)
  (header)
  (indexed_reposition)
  (index_hint)
  (join_by_sqldb)
  (keep_messages)
  (key_function)
  (landscape)
  (large)
  (last)
  (lookahead)
  (menubar)
  (message)
  (moveable)
  (multiple)
  (must_exist)
  (nested)
  (new)
  (new_instance)
  (new_modifier)
  (next)
  (not)
  (not_active)
  (no_apply)
  (no_array_message)
  (no_assign)
  (no_attr_list)
  (no_attr_space)
  (no_bind_where)
  (no_box)
  (no_column_scrolling)
  (no_convert)
  (no_convert_3d_colors)
  (no_debug)
  (no_echo)
  (no_empty_space)
  (no_error)
  (no_fill)
  (no_focus)
  (no_hide)
  (no_index_hint)
  (no_join_by_sqldb)
  (no_label)
  (no_labels)
  (no_lobs)
  (no_lock)
  (no_lookahead)
  (no_map)
  (no_message)
  (no_pause)
  (no_prefetch)
  (no_row_markers)
  (no_separate_connection)
  (no_tab_stop)
  (no_undo)
  (no_validate)
  (no_wait)
  (no_word_wrap)
  (ordered_join)
  (overlay)
  (override)
  (override_modifier)
  (paged)
  (page_bottom)
  (page_top)
  (pascal)
  (performance)
  (persistent)
  (portrait)
  (preselect)
  (prev)
  (primary)
  (rcode_information)
  (recursive)
  (reference_only)
  (replace)
  (reposition)
  (resizable)
  (retain_shape)
  (return_to_start_dir)
  (reverse_from)
  (rounded)
  (row)
  (rule)
  (save_as)
  (scope_modifier)
  (scrollbar_horizontal)
  (scrollbar_vertical)
  (scrolling)
  (separate_connection)
  (separators)
  (serializable)
  (serialization_modifier)
  (serialize_hidden)
  (share)
  (share_lock)
  (side_labels)
  (silent)
  (simple)
  (skip)
  (skip_group_duplicates)
  (sort)
  (space)
  (sql)
  (static_modifier)
  (stdcall)
  (stream_io)
  (stretch_to_fit)
  (submenu_help)
  (table_scan)
  (terminal)
  (text)
  (this_object)
  (this_procedure)
  (thread_safe)
  (three_d)
  (transaction)
  (transparent)
  (trim)
  (unbuffered)
  (unformatted)
  (unique)
  (unique_match)
  (unless_hidden)
  (up)
  (use_filename)
  (use_revvideo)
  (use_text)
  (use_underline)
  (use_widget_pool)
  (validate)
  (verbose)
  (word_index)
  "ABSTRACT"
  "ACCELERATOR"
  "ACCUM"
  "ACCUMULATE"
  "ACTIVE-WINDOW"
  "AGGREGATE"
  "ALERT-BOX"
  "ALIAS"
  "ALL"
  "AMBIGUOUS"
  "AND"
  "APPEND"
  "APPLICATION"
  "APPLY"
  "AS"
  "ASCENDING"
  "ASSEMBLY"
  "ASSIGN"
  "ASYNCHRONOUS"
  "AT"
  "AUTO-COMPLETION"
  "AUTO-RETURN"
  "AUTOMATIC"
  "AVAIL"
  "AVAILABLE"
  "AVERAGE"
  "BASE-KEY"
  "BEFORE-TABLE"
  "BEGINS"
  "BELL"
  "BGCOLOR"
  "BLANK"
  "BLINK-"
  "BLOCK-LEVEL"
  "BOTH"
  "BOTTOM"
  "BREAK"
  "BRIGHT-"
  "BROWSE"
  "BUFFER"
  "BUFFER-CHARS"
  "BUFFER-COMPARE"
  "BUFFER-COPY"
  "BUFFER-LINES"
  "BUFFER-NAME"
  "BUTTON"
  "BUTTONS"
  "BY"
  "BY-REFERENCE"
  "CACHE"
  "CACHE-SIZE"
  "CALL"
  "CAN-FIND"
  "CASE"
  "CATCH"
  "CHOOSE"
  "CLASS"
  "CLEAR"
  "CLIENT-PRINCIPAL"
  "CLIPBOARD"
  "CLOSE"
  "CODEPAGE"
  "COL"
  "COLLATE"
  "COLON"
  "COLON-ALIGNED"
  "COLOR"
  "COLOR-TABLE"
  "COLUMN"
  "COLUMN-BGCOLOR"
  "COLUMN-CODEPAGE"
  "COLUMN-DCOLOR"
  "COLUMN-FGCOLOR"
  "COLUMN-FONT"
  "COLUMN-LABEL"
  "COLUMN-OF"
  "COLUMN-PFCOLOR"
  "COLUMNS"
  "COMBO-BOX"
  "COMMAND"
  "COMPILE"
  "COMPILER"
  "COMPLETE"
  "CONNECT"
  "CONSTRUCTOR"
  "CONTEXT-HELP-ID"
  "CONTROL"
  "CONTROL-FRAME"
  "CONVERT"
  "COPY-LOB"
  "COUNT"
  "CREATE"
  "CURRENT"
  "CURRENT-CHANGED"
  "CURRENT-WINDOW"
  "CURSOR"
  "DATA-RELATION"
  "DATA-SOURCE"
  "DATABASE"
  "DATASET"
  "DATASET-HANDLE"
  "DCOLOR"
  "DDE"
  "DEBLANK"
  "DEBUG"
  "DEBUG-LIST"
  "DEBUGGER"
  "DECIMALS"
  "DEFAULT"
  "DEFAULT-EXTENSION"
  "DEFAULT-UNTRANSLATABLE"
  "DEFAULT-WINDOW"
  "DEFINE"
  "DELEGATE"
  "DELETE"
  "DELIMITER"
  "DESCENDING"
  "DESTRUCTOR"
  "DIALOG-BOX"
  "DICTIONARY"
  "DIR"
  "DISABLE"
  "DISABLE-AUTO-ZAP"
  "DISCONNECT"
  "DISPLAY"
  "DO"
  "DOS"
  "DOWN"
  "DUMP"
  "DYNAMIC-NEW"
  "EACH"
  "EDGE-CHARS"
  "EDGE-PIXELS"
  "EDITING"
  "EDITOR"
  "ELSE"
  "EMPTY"
  "ENABLE"
  "END"
  "END-KEY"
  "ENDKEY"
  "ENTRY"
  "ENUM"
  "EQ"
  "ERROR"
  "ERROR-STATUS"
  "EVENT"
  "EVENT-HANDLER"
  "EVENT-HANDLER-CONTEXT"
  "EVENT-PROCEDURE"
  "EVENTS"
  "EXCEPT"
  "EXCLUSIVE-LOCK"
  "EXPAND"
  "EXPORT"
  "EXTENDED"
  "EXTENT"
  "EXTERNAL"
  "FALSE"
  "FGCOLOR"
  "FIELD"
  "FIELDS"
  "FILE"
  "FILE-INFO"
  "FILL-IN"
  "FILTERS"
  "FINALLY"
  "FIND"
  "FIRST"
  "FIX-CODEPAGE"
  "FOCUS"
  "FONT"
  "FONT-TABLE"
  "FOR"
  "FORM"
  "FORMAT"
  "FRAME"
  "FREQUENCY"
  "FROM"
  "FUNCTION"
  "GE"
  "GET"
  "GET-DIR"
  "GET-FILE"
  "GET-KEY-VALUE"
  "GO-ON"
  "GROUP"
  "GT"
  "HELP"
  "HIDE"
  "HORIZONTAL"
  "IF"
  "IMAGE"
  "IMAGE-DOWN"
  "IMAGE-INSENSITIVE"
  "IMAGE-SIZE"
  "IMAGE-SIZE-CHARS"
  "IMAGE-SIZE-PIXELS"
  "IMAGE-UP"
  "IMPLEMENTS"
  "IMPORT"
  "IN"
  "INDEX"
  "INHERITS"
  "INITIAL"
  "INITIAL-DIR"
  "INITIAL-FILTER"
  "INNER-CHARS"
  "INNER-LINES"
  "INPUT"
  "INPUT-OUTPUT"
  "INSERT"
  "INTERFACE"
  "INTO"
  "IS"
  "ITEM"
  "KEY"
  "KEYS"
  "LABEL"
  "LABEL-BGCOLOR"
  "LABEL-DCOLOR"
  "LABEL-FGCOLOR"
  "LABEL-FONT"
  "LABEL-PFCOLOR"
  "LANGUAGES"
  "LARGE"
  "LARGE-TO-SMALL"
  "LAST"
  "LAST-EVENT"
  "LE"
  "LEAVE"
  "LEFT"
  "LEFT-ALIGNED"
  "LIKE"
  "LIKE-SEQUENTIAL"
  "LIST-ITEM-PAIRS"
  "LIST-ITEMS"
  "LISTING"
  "LOAD"
  "LOAD-PICTURE"
  "LOAD-RESULT-INTO"
  "LOB-DIR"
  "LOCKED"
  "LT"
  "MAP"
  "MATCHES"
  "MAX-CHARS"
  "MAX-DATA-GUESS"
  "MAX-ROWS"
  "MAX-SIZE"
  "MAX-VALUE"
  "MAXIMUM"
  "MENU"
  "MENU-ITEM"
  "MESSAGE"
  "MESSAGES"
  "METHOD"
  "MIN-SIZE"
  "MIN-VALUE"
  "MINIMUM"
  "MOD"
  "MODULO"
  "MOUSE-POINTER"
  "MULTIPLE"
  "NAMESPACE-PREFIX"
  "NAMESPACE-URI"
  "NATIVE"
  "NE"
  "NEW"
  "NEXT"
  "NEXT-PROMPT"
  "NO"
  "NO-APPLY"
  "NO-BOX"
  "NO-CONSOLE"
  "NO-CURRENT-VALUE"
  "NO-DRAG"
  "NO-ERROR"
  "NO-LABELS"
  "NO-LOCK"
  "NO-TAB-STOP"
  "NO-WAIT"
  "NO-WORD-WRAP"
  "NONE"
  "NORMAL"
  "NOT"
  "NUM-COPIES"
  "OBJECT"
  "OF"
  "OFF"
  "OK"
  "OK-CANCEL"
  "OLD"
  "ON"
  "OPEN"
  "OPTIONS"
  "OPTIONS-FILE"
  "OR"
  "ORDINAL"
  "OS-APPEND"
  "OS-COMMAND"
  "OS-COPY"
  "OS-CREATE-DIR"
  "OS-DELETE"
  "OS-DIR"
  "OS-RENAME"
  "OTHERWISE"
  "OUTER-JOIN"
  "OUTPUT"
  "OVERLAY"
  "PAGE"
  "PAGE-SIZE"
  "PAGE-WIDTH"
  "PARAM"
  "PARAMETER"
  "PARENT-FIELDS-AFTER"
  "PARENT-FIELDS-BEFORE"
  "PARENT-ID-FIELD"
  "PARENT-ID-RELATION"
  "PAUSE"
  "PERSISTENT"
  "PFCOLOR"
  "PREPROCESS"
  "PRESELECT"
  "PREV"
  "PRINTER"
  "PRINTER-SETUP"
  "PROC-HANDLE"
  "PROC-STATUS"
  "PROCEDURE"
  "PROCESS"
  "PROMPT"
  "PROMPT-FOR"
  "PROMSGS"
  "PROPATH"
  "PROPERTY"
  "PUBLISH"
  "PUT"
  "PUT-KEY-VALUE"
  "QUERY"
  "QUERY-TUNING"
  "QUIT"
  "RADIO-BUTTONS"
  "RADIO-SET"
  "RAW-TRANSFER"
  "RCODE-INFO"
  "READKEY"
  "RECID"
  "RECTANGLE"
  "RELATION-FIELDS"
  "RELEASE"
  "REPEAT"
  "REPOSITION"
  "RESULT"
  "RETRY"
  "RETRY-CANCEL"
  "RETURN"
  "RETURNS"
  "RIGHT"
  "RIGHT-ALIGNED"
  "ROUTINE-LEVEL"
  "ROW"
  "ROW-OF"
  "ROWID"
  "RUN"
  "RUN-PROCEDURE"
  "RVV-"
  "SAVE"
  "SAX-ATTRIBUTES"
  "SAX-READER"
  "SAX-WRITER"
  "SCREEN"
  "SCROLL"
  "SCROLLBAR-HORIZONTAL"
  "SCROLLBAR-VERTICAL"
  "SECTION"
  "SEEK"
  "SELECTION-LIST"
  "SELF"
  "SERIALIZE-NAME"
  "SERVER"
  "SERVER-SOCKET"
  "SESSION"
  "SET"
  "SET-BYTE-ORDER"
  "SET-POINTER-VALUE"
  "SET-SIZE"
  "SHARE-LOCK"
  "SHOW-STATS"
  "SIGNATURE"
  "SILENT"
  "SINGLE"
  "SIZE"
  "SIZE-CHARS"
  "SIZE-PIXELS"
  "SKIP"
  "SLIDER"
  "SOAP-HEADER"
  "SOAP-HEADER-ENTRYREF"
  "SOCKET"
  "SORT"
  "SOURCE"
  "SOURCE-PROCEDURE"
  "SPACE"
  "STARTING"
  "STATUS"
  "STOP"
  "STOP-AFTER"
  "STORED-PROC"
  "STORED-PROCEDURE"
  "STREAM"
  "STREAM-HANDLE"
  "STREAM-IO"
  "STRING-XREF"
  "SUB-AVERAGE"
  "SUB-COUNT"
  "SUB-MAXIMUM"
  "SUB-MENU"
  "SUB-MINIMUM"
  "SUB-TOTAL"
  "SUBSCRIBE"
  "SUPER"
  "SYSTEM-DIALOG"
  "SYSTEM-HELP"
  "TABLE"
  "TABLE-HANDLE"
  "TARGET"
  "TARGET-PROCEDURE"
  "TEMP-TABLE"
  "TENANT"
  "TENANT-WHERE"
  "TERMINAL"
  "TEXT"
  "TEXT-SEG-GROW"
  "THEN"
  "THIS-OBJECT"
  "THIS-PROCEDURE"
  "THROUGH"
  "THROW"
  "TIC-MARKS"
  "TIME"
  "TITLE"
  "TO"
  "TOGGLE-BOX"
  "TOOLTIP"
  "TOP"
  "TOPIC"
  "TOTAL"
  "TRANSACTION-MODE"
  "TRIGGER"
  "TRIGGERS"
  "TRUE"
  "TTCODEPAGE"
  "UNDERLINE"
  "UNDERLINE-"
  "UNDO"
  "UNFORMATTED"
  "UNIX"
  "UNLOAD"
  "UNSUBSCRIBE"
  "UNTIL"
  "UP"
  "UPDATE"
  "USE"
  "USE-INDEX"
  "USING"
  "V6FRAME"
  "VALIDATE"
  "VALUE"
  "VAR"
  "VARIABLE"
  "VERTICAL"
  "VIEW"
  "VIEW-AS"
  "VOID"
  "WAIT-FOR"
  "WHEN"
  "WHERE"
  "WHILE"
  "WIDGET"
  "WIDGET-ID"
  "WIDGET-POOL"
  "WIDTH"
  "WINDOW"
  "WITH"
  "WORK-TABLE"
  "WORKFILE"
  "WRITE"
  "X"
  "X-DOCUMENT"
  "X-NODEREF"
  "X-OF"
  "XCODE"
  "XML-DATA-TYPE"
  "XML-NODE-NAME"
  "XML-NODE-TYPE"
  "XREF"
  "XREF-XML"
  "Y"
  "Y-OF"
  "YES"
  "YES-NO"
  "YES-NO-CANCEL"
] @keyword
