import { kw } from "./helpers/keywords.js";

export const COMPARISON_OPERATORS = [
  "<>",
  ">",
  "<",
  ">=",
  "<=",
  kw("BEGINS"),
  kw("MATCHES"),
  kw("CONTAINS"),
  kw("EQ"),
  kw("NE"),
  kw("GT"),
  kw("LT"),
  kw("GE"),
  kw("LE"),
];

export const WIDGETS = [
  kw("WINDOW"),
  kw("BUTTON"),
  kw("FILL-IN"),
  kw("TOGGLE-BOX"),
  kw("RADIO-SET"),
  kw("EDITOR"),
  kw("SELECTION-LIST"),
  kw("COMBO-BOX"),
  kw("SLIDER"),
  kw("RECTANGLE"),
  kw("TEXT"),
  kw("IMAGE"),
  kw("BROWSE"),
  kw("QUERY"),
  kw("SUB-MENU"),
  kw("MENU-ITEM"),
  kw("MENU"),
];

export const inline = ($) => [
  $._kw_and,
  $._kw_bgcolor,
  $._kw_browse,
  $._kw_buffer,
  $._kw_class,
  $._kw_codepage,
  $._kw_column,
  $._kw_dcolor,
  $._kw_data_source,
  $._kw_down,
  $._kw_fgcolor,
  $._kw_from,
  $._kw_horizontal,
  $._kw_interface,
  $._kw_image,
  $._kw_into,
  $._kw_left,
  $._kw_except,
  $._kw_font,
  $._kw_inner_lines,
  $._kw_input,
  $._kw_or,
  $._kw_menu,
  $._kw_object,
  $._kw_old,
  $._kw_parameter,
  $._kw_pfcolor,
  $._kw_prompt,
  $._kw_query,
  $._kw_stream,
  $._kw_skip,
  $._kw_space,
  $._kw_table_handle,
  $._kw_triggers,
  $._kw_text,
  $._kw_tooltip,
  $._kw_vertical,
  $._kw_undo,
  $._kw_update,
  $._kw_validate,
  $._kw_while,
  $._kw_window,
  $._kw_value,
  $._kw_when,
  $._kw_x,
  $._kw_y,
  $._kw_context_help_id,
  $._kw_method,
  $._kw_enable,
  $._kw_label,
  $._kw_get,
  $._kw_first,
  $._kw_last,
  $._kw_where,
  $._kw_use_index,
  $._kw_size,
  $._kw_size_chars,
  $._kw_size_pixels,
  $._kw_table,
  $._kw_dataset_handle,
  $._kw_sub_menu,
  $._kw_widget_id,
  $._kw_open,
  $._kw_count,
  $._kw_call,
  $._kw_server,
  $._kw_rowid,
  $._kw_recid,
  $._kw_default,
  $._kw_button,
  $._kw_stop,
  $._kw_display,
  $._kw_run,
  $._kw_constructor,
  $._kw_target,
  $._kw_source,
  $._kw_xml_node_type,
  $._procedure_keyword,
  $._routine_access_modifier,
  $._for_keyword,
  $._as_keyword,
];

export default ({ kw }) => ({
  _for_keyword: ($) => kw("FOR"),
  _to_keyword: ($) => kw("TO"),
  // oxlint-disable-next-line tree-sitter-optimize/shared-keyword-inline
  _in_keyword: ($) => kw("IN"),
  _define_keyword: ($) => kw("DEFINE", { offset: 3 }),
  _end_keyword: ($) => kw("END"),
  _by_keyword: ($) => kw("BY"),
  _as_keyword: ($) => kw("AS"),
  _no_undo_keyword: ($) => kw("NO-UNDO"),
  _of_keyword: ($) => kw("OF"),
  _like_keyword: ($) => kw("LIKE"),
  _row_keyword: ($) => kw("ROW"),
  // oxlint-disable-next-line tree-sitter-optimize/shared-keyword-inline
  _new_keyword: ($) => kw("NEW"),
  _dataset_keyword: ($) => kw("DATASET"),
  _on_keyword: ($) => kw("ON"),
  _at_keyword: ($) => kw("AT"),
  _using_keyword: ($) => kw("USING"),
  _help_keyword: ($) => kw("HELP"),
  _kw_and: ($) => kw("AND"),
  _kw_bgcolor: ($) => kw("BGCOLOR"),
  _kw_browse: ($) => kw("BROWSE"),
  _kw_buffer: ($) => kw("BUFFER"),
  _kw_class: ($) => kw("CLASS"),
  _kw_codepage: ($) => kw("CODEPAGE"),
  _kw_column: ($) => kw("COLUMN"),
  _kw_dcolor: ($) => kw("DCOLOR"),
  _kw_data_source: ($) => kw("DATA-SOURCE"),
  _kw_down: ($) => kw("DOWN"),
  _kw_fgcolor: ($) => kw("FGCOLOR"),
  _kw_from: ($) => kw("FROM"),
  _kw_horizontal: ($) => kw("HORIZONTAL"),
  _kw_interface: ($) => kw("INTERFACE"),
  _kw_image: ($) => kw("IMAGE"),
  _kw_into: ($) => kw("INTO"),
  _kw_left: ($) => kw("LEFT"),
  _kw_except: ($) => kw("EXCEPT"),
  _kw_font: ($) => kw("FONT"),
  _kw_inner_lines: ($) => kw("INNER-LINES"),
  _kw_input: ($) => kw("INPUT"),
  _kw_or: ($) => kw("OR"),
  _kw_menu: ($) => kw("MENU"),
  _kw_object: ($) => kw("OBJECT"),
  _kw_old: ($) => kw("OLD"),
  _kw_parameter: ($) => kw("PARAMETER", { offset: 5 }),
  _kw_pfcolor: ($) => kw("PFCOLOR"),
  _kw_prompt: ($) => kw("PROMPT"),
  _kw_query: ($) => kw("QUERY"),
  _kw_stream: ($) => kw("STREAM"),
  _kw_skip: ($) => kw("SKIP"),
  _kw_space: ($) => kw("SPACE"),
  _kw_table_handle: ($) => kw("TABLE-HANDLE"),
  _kw_triggers: ($) => kw("TRIGGERS"),
  _kw_text: ($) => kw("TEXT"),
  _kw_tooltip: ($) => kw("TOOLTIP"),
  _kw_vertical: ($) => kw("VERTICAL"),
  _kw_undo: ($) => kw("UNDO"),
  _kw_update: ($) => kw("UPDATE"),
  _kw_validate: ($) => kw("VALIDATE"),
  _kw_while: ($) => kw("WHILE"),
  _kw_window: ($) => kw("WINDOW"),
  _kw_value: ($) => kw("VALUE"),
  _kw_when: ($) => kw("WHEN"),
  _kw_x: ($) => kw("X"),
  _kw_y: ($) => kw("Y"),
  _kw_label: ($) => kw("LABEL"),
  _kw_get: ($) => kw("GET"),
  _kw_first: ($) => kw("FIRST"),
  _kw_last: ($) => kw("LAST"),
  _kw_where: ($) => kw("WHERE"),
  _kw_use_index: ($) => kw("USE-INDEX"),
  _kw_size: ($) => kw("SIZE"),
  _kw_size_chars: ($) => kw("SIZE-CHARS"),
  _kw_size_pixels: ($) => kw("SIZE-PIXELS"),
  _kw_table: ($) => kw("TABLE"),
  _kw_dataset_handle: ($) => kw("DATASET-HANDLE"),
  _kw_sub_menu: ($) => kw("SUB-MENU"),
  _kw_widget_id: ($) => kw("WIDGET-ID"),
  _kw_open: ($) => kw("OPEN"),
  _kw_count: ($) => kw("COUNT"),
  _kw_call: ($) => kw("CALL"),
  _kw_server: ($) => kw("SERVER"),
  _kw_rowid: ($) => kw("ROWID"),
  _kw_recid: ($) => kw("RECID"),
  _kw_default: ($) => kw("DEFAULT"),
  _kw_button: ($) => kw("BUTTON"),
  _kw_stop: ($) => kw("STOP"),
  _kw_display: ($) => kw("DISPLAY"),
  _kw_run: ($) => kw("RUN"),
  _kw_constructor: ($) => kw("CONSTRUCTOR"),
  _kw_target: ($) => kw("TARGET"),
  _kw_source: ($) => kw("SOURCE"),
  _kw_xml_node_type: ($) => kw("XML-NODE-TYPE"),
  _kw_context_help_id: ($) => kw("CONTEXT-HELP-ID"),
  _kw_method: ($) => kw("METHOD"),
  _kw_enable: ($) => kw("ENABLE"),
  _procedure_keyword: ($) => kw("PROCEDURE", { offset: 4 }),
  _delete_keyword: ($) => kw("DELETE"),
  _close_keyword: ($) => kw("CLOSE"),
  _with_keyword: ($) => kw("WITH"),
  // oxlint-disable-next-line tree-sitter-optimize/choice-subset
  _routine_access_modifier: ($) =>
    choice(
      // oxlint-disable-next-line tree-sitter-optimize/inline-keyword-owner
      alias(kw("PRIVATE"), $.access_modifier),
      alias(kw("PROTECTED"), $.access_modifier),
      // oxlint-disable-next-line tree-sitter-optimize/inline-keyword-owner
      alias(kw("PUBLIC"), $.access_modifier),
    ),
  // oxlint-disable-next-line tree-sitter-optimize/shared-keyword-inline
  _not_keyword: ($) => kw("NOT"),
});
