import { kw } from "./helpers/keywords.js";

export const COMPARISON_OPERATORS = [
  "<>",
  ">",
  "<",
  ">=",
  "<=",
  kw("BEGINS"),
  kw("MATCHES"),
  kw("CONTAINS"),
  kw("EQ"),
  kw("NE"),
  kw("GT"),
  kw("LT"),
  kw("GE"),
  kw("LE"),
];

export const WIDGETS = [
  kw("WINDOW"),
  kw("BUTTON"),
  kw("FILL-IN"),
  kw("TOGGLE-BOX"),
  kw("RADIO-SET"),
  kw("EDITOR"),
  kw("SELECTION-LIST"),
  kw("COMBO-BOX"),
  kw("SLIDER"),
  kw("RECTANGLE"),
  kw("TEXT"),
  kw("IMAGE"),
  kw("BROWSE"),
  kw("QUERY"),
  kw("SUB-MENU"),
  kw("MENU-ITEM"),
  kw("MENU"),
];

export const inline = ($) => [
  $._kw_and,
  $._kw_alias,
  $._kw_average,
  $._kw_maximum,
  $._kw_application,
  $._kw_else,
  $._kw_assign,
  $._kw_bell,
  $._kw_bgcolor,
  $._kw_browse,
  $._kw_break,
  $._kw_buffer,
  $._kw_back_tab,
  $._kw_class,
  $._kw_codepage,
  $._kw_colon,
  $._kw_column,
  $._kw_column_of,
  $._kw_keys,
  $._kw_convert,
  $._kw_color,
  $._kw_collate,
  $._kw_dcolor,
  $._kw_data_source,
  $._kw_down,
  $._kw_each,
  $._kw_fgcolor,
  $._kw_from,
  $._kw_forwards,
  $._kw_horizontal,
  $._kw_interface,
  $._kw_inherits,
  $._kw_image,
  $._kw_into,
  $._kw_index,
  $._kw_is,
  $._kw_left,
  $._kw_leave,
  $._kw_except,
  $._kw_font,
  $._kw_inner_lines,
  $._kw_input,
  $._kw_input_output,
  $._kw_or,
  $._kw_menu,
  $._kw_object,
  $._kw_old,
  $._kw_parameter,
  $._kw_pfcolor,
  $._kw_prompt,
  $._kw_propath,
  $._kw_put,
  $._kw_query,
  $._kw_quit,
  $._kw_stream,
  $._kw_stream_handle,
  $._kw_skip,
  $._kw_scroll,
  $._kw_silent,
  $._kw_space,
  $._kw_table_handle,
  $._kw_triggers,
  $._kw_text,
  $._kw_then,
  $._kw_through,
  $._kw_tooltip,
  $._kw_vertical,
  $._kw_undo,
  $._kw_up,
  $._kw_update,
  $._kw_write,
  $._kw_validate,
  $._kw_void,
  $._kw_while,
  $._kw_window,
  $._kw_overlay,
  $._kw_output,
  $._kw_value,
  $._kw_when,
  $._kw_x,
  $._kw_y,
  $._kw_context_help_id,
  $._kw_method,
  $._kw_messages,
  $._kw_enable,
  $._kw_enum,
  $._kw_error,
  $._kw_end_error,
  $._kw_endkey,
  $._kw_external,
  $._kw_if,
  $._kw_editor,
  $._kw_label,
  $._kw_large,
  $._kw_load,
  $._kw_map,
  $._kw_file,
  $._kw_fill_in,
  $._kw_format,
  $._kw_get,
  $._kw_key,
  $._kw_group,
  $._kw_list_items,
  $._kw_list_item_pairs,
  $._kw_go,
  $._kw_first,
  $._kw_focus,
  $._kw_find,
  $._kw_last,
  $._kw_next,
  $._kw_prev,
  $._kw_next_frame,
  $._kw_prev_frame,
  $._kw_where,
  $._kw_use_index,
  $._kw_native,
  $._kw_size,
  $._kw_size_chars,
  $._kw_size_pixels,
  $._kw_page_size,
  $._kw_table,
  $._kw_tab,
  $._kw_extent,
  $._kw_dataset_handle,
  $._kw_sub_menu,
  $._kw_selection_list,
  $._kw_menu_item,
  $._kw_stored_procedure,
  $._kw_stream_io,
  $._kw_widget_id,
  $._kw_slider,
  $._kw_radio_set,
  $._kw_combo_box,
  $._kw_open,
  $._kw_off,
  $._kw_count,
  $._kw_current,
  $._kw_cursor,
  $._kw_ordinal,
  $._kw_throw,
  $._kw_call,
  $._kw_command,
  $._kw_connect,
  $._kw_server,
  $._kw_rowid,
  $._kw_row_of,
  $._kw_recid,
  $._kw_default,
  $._kw_button,
  $._kw_stop,
  $._kw_display,
  $._kw_run,
  $._kw_super,
  $._kw_constructor,
  $._kw_destructor,
  $._kw_set,
  $._kw_cache,
  $._kw_create,
  $._kw_clear,
  $._kw_clipboard,
  $._kw_auto_return,
  $._kw_decimals,
  $._kw_disable,
  $._kw_disable_auto_zap,
  $._kw_blank,
  $._kw_deblank,
  $._kw_max_chars,
  $._kw_min_size,
  $._kw_minimum,
  $._kw_total,
  $._kw_return,
  $._kw_retain,
  $._kw_no_apply,
  $._kw_no_tab_stop,
  $._kw_no_word_wrap,
  $._kw_unformatted,
  $._kw_normal,
  $._kw_release,
  $._kw_save,
  $._kw_seek,
  $._kw_target,
  $._kw_title,
  $._kw_source,
  $._kw_xml_node_type,
  $._kw_procedure,
  $._routine_access_modifier,
  $._kw_for,
  $._kw_as,
];

export default ({ kw }) => ({
  _kw_for: ($) => kw("FOR"),
  _kw_to: ($) => kw("TO"),
  // oxlint-disable-next-line tree-sitter-optimize/shared-keyword-inline
  _kw_in: ($) => kw("IN"),
  _kw_define: ($) => kw("DEFINE", { offset: 3 }),
  _kw_end: ($) => kw("END"),
  _kw_by: ($) => kw("BY"),
  _kw_as: ($) => kw("AS"),
  _kw_no_undo: ($) => kw("NO-UNDO"),
  _kw_of: ($) => kw("OF"),
  _kw_like: ($) => kw("LIKE"),
  _row_keyword: ($) => kw("ROW"),
  // oxlint-disable-next-line tree-sitter-optimize/shared-keyword-inline
  _new_keyword: ($) => kw("NEW"),
  _dataset_keyword: ($) => kw("DATASET"),
  _on_keyword: ($) => kw("ON"),
  _at_keyword: ($) => kw("AT"),
  _using_keyword: ($) => kw("USING"),
  _help_keyword: ($) => kw("HELP"),
  _kw_and: ($) => kw("AND"),
  _kw_alias: ($) => kw("ALIAS"),
  _kw_average: ($) => kw("AVERAGE"),
  _kw_maximum: ($) => kw("MAXIMUM"),
  _kw_application: ($) => kw("APPLICATION"),
  _kw_else: ($) => kw("ELSE"),
  _kw_assign: ($) => kw("ASSIGN"),
  _kw_bell: ($) => kw("BELL"),
  _kw_bgcolor: ($) => kw("BGCOLOR"),
  _kw_browse: ($) => kw("BROWSE"),
  _kw_break: ($) => kw("BREAK"),
  _kw_buffer: ($) => kw("BUFFER"),
  _kw_back_tab: ($) => kw("BACK-TAB"),
  _kw_class: ($) => kw("CLASS"),
  _kw_codepage: ($) => kw("CODEPAGE"),
  _kw_colon: ($) => kw("COLON"),
  _kw_column: ($) => kw("COLUMN"),
  _kw_column_of: ($) => kw("COLUMN-OF"),
  _kw_keys: ($) => kw("KEYS"),
  _kw_color: ($) => kw("COLOR"),
  _kw_collate: ($) => kw("COLLATE"),
  _kw_dcolor: ($) => kw("DCOLOR"),
  _kw_data_source: ($) => kw("DATA-SOURCE"),
  _kw_down: ($) => kw("DOWN"),
  _kw_each: ($) => kw("EACH"),
  _kw_fgcolor: ($) => kw("FGCOLOR"),
  _kw_from: ($) => kw("FROM"),
  _kw_forwards: ($) => kw("FORWARDS", { alias: "FORWARD", offset: 7 }),
  _kw_horizontal: ($) => kw("HORIZONTAL"),
  _kw_interface: ($) => kw("INTERFACE"),
  _kw_inherits: ($) => kw("INHERITS"),
  _kw_image: ($) => kw("IMAGE"),
  _kw_into: ($) => kw("INTO"),
  _kw_index: ($) => kw("INDEX"),
  _kw_is: ($) => kw("IS"),
  _kw_left: ($) => kw("LEFT"),
  _kw_leave: ($) => kw("LEAVE"),
  _kw_except: ($) => kw("EXCEPT"),
  _kw_font: ($) => kw("FONT"),
  _kw_inner_lines: ($) => kw("INNER-LINES"),
  _kw_input: ($) => kw("INPUT"),
  _kw_input_output: ($) => kw("INPUT-OUTPUT", { offset: 7 }),
  _kw_or: ($) => kw("OR"),
  _kw_menu: ($) => kw("MENU"),
  _kw_object: ($) => kw("OBJECT"),
  _kw_old: ($) => kw("OLD"),
  _kw_parameter: ($) => kw("PARAMETER", { offset: 5 }),
  _kw_pfcolor: ($) => kw("PFCOLOR"),
  _kw_prompt: ($) => kw("PROMPT"),
  _kw_propath: ($) => kw("PROPATH"),
  _kw_put: ($) => kw("PUT"),
  _kw_query: ($) => kw("QUERY"),
  _kw_quit: ($) => kw("QUIT"),
  _kw_stream: ($) => kw("STREAM"),
  _kw_stream_handle: ($) => kw("STREAM-HANDLE"),
  _kw_skip: ($) => kw("SKIP"),
  _kw_scroll: ($) => kw("SCROLL"),
  _kw_silent: ($) => kw("SILENT"),
  _kw_space: ($) => kw("SPACE"),
  _kw_table_handle: ($) => kw("TABLE-HANDLE"),
  _kw_triggers: ($) => kw("TRIGGERS"),
  _kw_text: ($) => kw("TEXT"),
  _kw_then: ($) => kw("THEN"),
  _kw_through: ($) => kw("THROUGH"),
  _kw_tooltip: ($) => kw("TOOLTIP"),
  _kw_vertical: ($) => kw("VERTICAL"),
  _kw_undo: ($) => kw("UNDO"),
  _kw_up: ($) => kw("UP"),
  _kw_update: ($) => kw("UPDATE"),
  _kw_write: ($) => kw("WRITE"),
  _kw_validate: ($) => kw("VALIDATE"),
  _kw_void: ($) => kw("VOID"),
  _kw_while: ($) => kw("WHILE"),
  _kw_window: ($) => kw("WINDOW"),
  _kw_overlay: ($) => kw("OVERLAY"),
  _kw_output: ($) => kw("OUTPUT"),
  _kw_value: ($) => kw("VALUE"),
  _kw_when: ($) => kw("WHEN"),
  _kw_x: ($) => kw("X"),
  _kw_y: ($) => kw("Y"),
  _kw_label: ($) => kw("LABEL"),
  _kw_large: ($) => kw("LARGE"),
  _kw_load: ($) => kw("LOAD"),
  _kw_map: ($) => kw("MAP"),
  _kw_file: ($) => kw("FILE"),
  _kw_fill_in: ($) => kw("FILL-IN"),
  _kw_format: ($) => kw("FORMAT", { offset: 4 }),
  _kw_get: ($) => kw("GET"),
  _kw_key: ($) => kw("KEY"),
  _kw_group: ($) => kw("GROUP"),
  _kw_list_items: ($) => kw("LIST-ITEMS"),
  _kw_list_item_pairs: ($) => kw("LIST-ITEM-PAIRS"),
  _kw_go: ($) => kw("GO"),
  _kw_first: ($) => kw("FIRST"),
  _kw_focus: ($) => kw("FOCUS"),
  _kw_find: ($) => kw("FIND"),
  _kw_last: ($) => kw("LAST"),
  _kw_next: ($) => kw("NEXT"),
  _kw_prev: ($) => kw("PREV"),
  _kw_next_frame: ($) => kw("NEXT-FRAME"),
  _kw_prev_frame: ($) => kw("PREV-FRAME"),
  _kw_where: ($) => kw("WHERE"),
  _kw_use_index: ($) => kw("USE-INDEX"),
  _kw_native: ($) => kw("NATIVE"),
  _kw_size: ($) => kw("SIZE"),
  _kw_size_chars: ($) => kw("SIZE-CHARS"),
  _kw_size_pixels: ($) => kw("SIZE-PIXELS"),
  _kw_page_size: ($) => kw("PAGE-SIZE"),
  _kw_table: ($) => kw("TABLE"),
  _kw_tab: ($) => kw("TAB"),
  _kw_convert: ($) => kw("CONVERT"),
  _kw_extent: ($) => kw("EXTENT"),
  _kw_dataset_handle: ($) => kw("DATASET-HANDLE"),
  _kw_sub_menu: ($) => kw("SUB-MENU"),
  _kw_selection_list: ($) => kw("SELECTION-LIST"),
  _kw_menu_item: ($) => kw("MENU-ITEM"),
  _kw_stored_procedure: ($) => kw("STORED-PROCEDURE"),
  _kw_stream_io: ($) => kw("STREAM-IO"),
  _kw_widget_id: ($) => kw("WIDGET-ID"),
  _kw_slider: ($) => kw("SLIDER"),
  _kw_radio_set: ($) => kw("RADIO-SET"),
  _kw_combo_box: ($) => kw("COMBO-BOX"),
  _kw_open: ($) => kw("OPEN"),
  _kw_off: ($) => kw("OFF"),
  _kw_count: ($) => kw("COUNT"),
  _kw_current: ($) => kw("CURRENT"),
  _kw_cursor: ($) => kw("CURSOR"),
  _kw_ordinal: ($) => kw("ORDINAL"),
  _kw_throw: ($) => kw("THROW"),
  _kw_call: ($) => kw("CALL"),
  _kw_command: ($) => kw("COMMAND"),
  _kw_connect: ($) => kw("CONNECT"),
  _kw_server: ($) => kw("SERVER"),
  _kw_rowid: ($) => kw("ROWID"),
  _kw_row_of: ($) => kw("ROW-OF"),
  _kw_recid: ($) => kw("RECID"),
  _kw_default: ($) => kw("DEFAULT"),
  _kw_button: ($) => kw("BUTTON"),
  _kw_stop: ($) => kw("STOP"),
  _kw_display: ($) => kw("DISPLAY"),
  _kw_run: ($) => kw("RUN"),
  _kw_super: ($) => kw("SUPER"),
  _kw_constructor: ($) => kw("CONSTRUCTOR"),
  _kw_destructor: ($) => kw("DESTRUCTOR"),
  _kw_set: ($) => kw("SET"),
  _kw_cache: ($) => kw("CACHE"),
  _kw_create: ($) => kw("CREATE"),
  _kw_clear: ($) => kw("CLEAR"),
  _kw_clipboard: ($) => kw("CLIPBOARD"),
  _kw_auto_return: ($) => kw("AUTO-RETURN"),
  _kw_decimals: ($) => kw("DECIMALS"),
  _kw_disable: ($) => kw("DISABLE"),
  _kw_disable_auto_zap: ($) => kw("DISABLE-AUTO-ZAP"),
  _kw_blank: ($) => kw("BLANK"),
  _kw_deblank: ($) => kw("DEBLANK"),
  _kw_max_chars: ($) => kw("MAX-CHARS"),
  _kw_min_size: ($) => kw("MIN-SIZE"),
  _kw_minimum: ($) => kw("MINIMUM"),
  _kw_total: ($) => kw("TOTAL"),
  _kw_return: ($) => kw("RETURN"),
  _kw_retain: ($) => kw("RETAIN"),
  _kw_no_apply: ($) => kw("NO-APPLY"),
  _kw_no_tab_stop: ($) => kw("NO-TAB-STOP"),
  _kw_no_word_wrap: ($) => kw("NO-WORD-WRAP"),
  _kw_unformatted: ($) => kw("UNFORMATTED"),
  _kw_normal: ($) => kw("NORMAL"),
  _kw_release: ($) => kw("RELEASE"),
  _kw_save: ($) => kw("SAVE"),
  _kw_seek: ($) => kw("SEEK"),
  _kw_target: ($) => kw("TARGET"),
  _kw_title: ($) => kw("TITLE"),
  _kw_source: ($) => kw("SOURCE"),
  _kw_xml_node_type: ($) => kw("XML-NODE-TYPE"),
  _kw_context_help_id: ($) => kw("CONTEXT-HELP-ID"),
  _kw_method: ($) => kw("METHOD"),
  _kw_messages: ($) => kw("MESSAGES"),
  _kw_enable: ($) => kw("ENABLE"),
  _kw_enum: ($) => kw("ENUM"),
  _kw_error: ($) => kw("ERROR"),
  _kw_end_error: ($) => kw("END-ERROR"),
  _kw_endkey: ($) => kw("ENDKEY"),
  _kw_external: ($) => kw("EXTERNAL"),
  _kw_if: ($) => kw("IF"),
  _kw_editor: ($) => kw("EDITOR"),
  _kw_procedure: ($) => kw("PROCEDURE", { offset: 4 }),
  _delete_keyword: ($) => kw("DELETE"),
  _close_keyword: ($) => kw("CLOSE"),
  _with_keyword: ($) => kw("WITH"),
  // oxlint-disable-next-line tree-sitter-optimize/choice-subset
  _routine_access_modifier: ($) =>
    choice(
      // oxlint-disable-next-line tree-sitter-optimize/inline-keyword-owner
      alias(kw("PRIVATE"), $.access_modifier),
      alias(kw("PROTECTED"), $.access_modifier),
      // oxlint-disable-next-line tree-sitter-optimize/inline-keyword-owner
      alias(kw("PUBLIC"), $.access_modifier),
    ),
  // oxlint-disable-next-line tree-sitter-optimize/shared-keyword-inline
  _not_keyword: ($) => kw("NOT"),
});
