// Statement-related disambiguation plumbing

module.exports = ({ tkw }) => ({
  expression_statement: ($) =>
    prec(
      -1,
      seq(
        $._statement_expression,
        optional(alias($.__expression_no_error, $.no_error)),
        $._terminator,
      ),
    ),
  __expression_no_error: ($) => tkw("NO-ERROR"),

  _statement: ($) =>
    choice(
      // Extras-like
      $.preprocessor_directive,
      $.include,

      // Definitions
      $.buffer_definition,
      $.temp_table_definition,
      $.work_table_definition,
      $.workfile_definition,
      $.variable_definition,
      $.parameter_definition,
      $.procedure_definition,
      $.procedure_forward_definition,
      $.function_definition,
      $.function_forward_definition,
      $.stream_definition,
      $.image_definition,
      $.query_definition,
      $.class_definition,
      $.interface_definition,
      $.dataset_definition,
      $.button_definition,
      $.rectangle_definition,
      $.event_definition,
      $.menu_definition,
      $.submenu_definition,

      // ABL Statements
      $.enum_statement,
      $.var_statement,
      $.if_statement,
      $.do_block,
      $.for_each_statement,
      $.find_statement,
      $.repeat_statement,
      $.display_statement,
      $.accumulate_statement,
      $.aggregate_statement,
      $.empty_temp_table_statement,
      $.empty_statement,
      $.block_level_on_error_statement,
      $.routine_level_on_error_statement,
      $.export_statement,
      $.assign_statement,
      $.annotation_statement,
      $.run_statement,
      $.run_stored_procedure_statement,
      $.create_statement,
      $.create_socket_statement,
      $.delete_statement,
      $.delete_object_statement,
      $.buffer_compare_statement,
      $.buffer_copy_statement,
      $.call_statement,
      $.copy_lob_statement,
      $.convert_statement,
      $.disable_triggers_statement,
      $.disable_statement,
      $.finally_statement,
      $.fix_codepage_statement,
      $.input_statement,
      $.input_clear_statement,
      $.input_output_statement,
      $.input_through_statement,
      $.import_statement,
      $.insert_statement,
      $.load_picture_statement,
      $.message_statement,
      $.overlay_statement,
      $.put_statement,
      $.put_cursor_statement,
      $.put_key_value_statement,
      $.put_screen_statement,
      $.on_statement,
      $.using_statement,
      $.use_statement,
      $.output_statement,
      $.os_delete_statement,
      $.os_command_statement,
      $.pause_statement,
      $.propath_statement,
      $.promsgs_statement,
      $.next_statement,
      $.next_prompt_statement,
      $.leave_statement,
      $.load_statement,
      $.get_key_value_statement,
      $.release_statement,
      $.release_external_statement,
      $.release_object_statement,
      $.case_statement,
      $.catch_statement,
      $.close_stored_procedure_statement,
      $.return_statement,
      $.save_cache_statement,
      $.set_byte_order_statement,
      $.set_pointer_value_statement,
      $.set_size_statement,
      $.set_statement,
      $.seek_statement,
      $.show_stats_statement,
      $.undo_statement,
      $.wait_for_statement,
      $.apply_statement,
      $.bell_statement,
      $.clear_statement,
      $.close_query_statement,
      $.color_statement,
      $.connect_statement,
      $.dictionary_statement,
      $.disconnect_statement,
      $.dos_statement,
      $.down_statement,
      $.enable_statement,
      $.form_statement,
      $.get_statement,
      $.hide_statement,
      $.open_query_statement,
      $.os_append_statement,
      $.os_copy_statement,
      $.os_create_dir_statement,
      $.os_rename_statement,
      $.page_statement,
      $.process_events_statement,
      $.prompt_for_statement,
      $.publish_statement,
      $.quit_statement,
      $.raw_transfer_statement,
      $.readkey_statement,
      $.reposition_statement,
      $.scroll_statement,
      $.status_statement,
      $.stop_statement,
      $.subscribe_statement,
      $.super_statement,
      $.terminal_statement,
      $.transaction_mode_statement,
      $.underline_statement,
      $.unix_statement,
      $.unload_statement,
      $.unsubscribe_statement,
      $.up_statement,
      $.update_statement,
      $.validate_statement,
      $.view_statement,
      $.assignment_statement,
      $.expression_statement,
      $.compile_statement,

      // TODO: statements that are hard to integrate due to state explosion or bugs
      // $.frame_definition // Completely broken
      // $.choose_statement, // +~4893 states, exceeds STATE_COUNT limit
      // $.browse_definition, // Too complex, exceeds state count
      // $.system_dialog_get_file_statement, // +~60000 states, exceeds STATE_COUNT limit
      // $.system_dialog_color_statement
      // $.system_dialog_font_statement
      // $.system_dialog_get_dir_statement,
      // $.system_dialog_printer_setup_statement,
    ),
});
