// Just aggregator of statements to avoid growing core context
// Leading comments indicate approximate state cost
// Run `bun run check:statements` to retrieve the costs

module.exports = () => ({
  _statement: ($) =>
    choice(
      // Extras-like
      $.preprocessor_directive,
      alias($.include_expression, $.include),
      $.empty_statement,

      // Definitions
      /* 254 */ $.buffer_definition,
      /* 5669 */ $.temp_table_definition,
      /* 1236 */ $.image_definition,
      /* 2030 */ $.browse_definition,
      /* 500 */ $.frame_definition,
      /* 390 */ $.class_definition,
      /* 329 */ $.data_source_definition,
      /* 344 */ $.query_definition,
      /* 190 */ $.variable_definition,
      /* 140 */ $.menu_definition,
      /* 195 */ $.function_definition,
      /* 86 */ $.button_definition,
      /* 99 */ $.work_table_definition,
      /* 80 */ $.rectangle_definition,
      /* 70 */ $.submenu_definition,
      /* 64 */ $.workfile_definition,
      /* 64 */ $.dataset_definition,
      /* 60 */ $.procedure_definition,
      /* 60 */ $.interface_definition,
      /* 89 */ $.function_forward_definition,
      /* 59 */ $.stream_definition,
      /* 40 */ $.parameter_definition,
      /* 65 */ $.event_definition,
      /* 20 */ $.procedure_forward_definition,

      // ABL Statements
      /* 9440 */ $.input_statement,
      /* 4980 */ $.choose_statement,
      /* 2660 */ $.input_through_statement,
      /* 1955 */ $.open_query_statement,
      /* 983 */ $.do_block,
      /* 815 */ $.buffer_compare_statement,
      /* 643 */ $.for_each_statement,
      /* 525 */ $.hide_statement,
      /* 500 */ $.subscribe_statement,
      /* 455 */ $.prompt_for_statement,
      /* 450 */ $.pause_statement,
      /* 223 */ $.repeat_statement,
      /* 315 */ $.set_statement,
      /* 300 */ $.enable_statement,
      /* 290 */ $.output_statement,
      /* 280 */ $.unsubscribe_statement,
      /* 255 */ $.import_statement,
      /* 220 */ $.insert_statement,
      /* 215 */ $.reposition_statement,
      /* 210 */ $.run_stored_procedure_statement,
      /* 200 */ $.input_output_statement,
      /* 195 */ $.put_screen_statement,
      /* 180 */ $.save_cache_statement,
      /* 180 */ $.overlay_statement,
      /* 175 */ $.load_statement,
      /* 172 */ $.put_statement,
      /* 170 */ $.message_statement,
      /* 165 */ $.wait_for_statement,
      /* 160 */ $.view_statement,
      /* 155 */ $.put_key_value_statement,
      /* 145 */ $.update_statement,
      /* 140 */ $.disable_statement,
      /* 140 */ $.status_statement,
      /* 135 */ $.color_statement,
      /* 129 */ $.on_statement,
      /* 128 */ $.if_statement,
      /* 125 */ $.seek_statement,
      /* 115 */ $.close_stored_procedure_statement,
      /* 115 */ $.undo_statement,
      /* 95 */ $.put_cursor_statement,
      /* 95 */ $.case_statement,
      /* 90 */ $.compile_statement,
      /* 90 */ $.find_statement,
      /* 85 */ $.raw_transfer_statement,
      /* 80 */ $.export_statement,
      /* 80 */ $.clear_statement,
      /* 80 */ $.down_statement,
      /* 80 */ $.up_statement,
      /* 75 */ $.scroll_statement,
      /* 70 */ $.get_key_value_statement,
      /* 70 */ $.dos_statement,
      /* 70 */ $.unix_statement,
      /* 70 */ $.enum_statement,
      /* 65 */ $.var_statement,
      /* 65 */ $.aggregate_statement,
      /* 65 */ $.copy_lob_statement,
      /* 65 */ $.convert_statement,
      /* 60 */ $.buffer_copy_statement,
      /* 80 */ $.catch_statement,
      /* 60 */ $.connect_statement,
      /* 60 */ $.disable_triggers_statement,
      /* 60 */ $.disconnect_statement,
      /* 60 */ $.readkey_statement,
      /* 55 */ $.os_command_statement,
      /* 55 */ $.publish_statement,
      /* 50 */ $.release_external_statement,
      /* 50 */ $.get_statement,
      /* 50 */ $.underline_statement,
      /* 45 */ $.annotation_statement,
      /* 45 */ $.assign_statement,
      /* 45 */ $.error_scope_statement,
      /* 40 */ $.release_object_statement,
      /* 35 */ $.display_statement,
      /* 35 */ $.apply_statement,
      /* 35 */ $.fix_codepage_statement,
      /* 35 */ $.set_byte_order_statement,
      /* 35 */ $.set_pointer_value_statement,
      /* 35 */ $.set_size_statement,
      /* 32 */ $.run_statement,
      /* 30 */ $.accumulate_statement,
      /* 30 */ $.call_statement,
      /* 30 */ $.create_socket_statement,
      /* 30 */ $.delete_object_statement,
      /* 30 */ $.empty_temp_table_statement,
      /* 30 */ $.finally_statement,
      /* 30 */ $.os_delete_statement,
      /* 30 */ $.transaction_mode_statement,
      /* 30 */ $.use_statement,
      /* 30 */ $.using_statement,
      /* 30 */ $.validate_statement,
      /* 30 */ $.assignment_statement,
      /* 25 */ $.close_query_statement,
      /* 25 */ $.form_statement,
      /* 25 */ $.next_prompt_statement,
      /* 25 */ $.propath_statement,
      /* 25 */ $.promsgs_statement,
      /* 25 */ $.return_statement,
      /* 25 */ $.unload_statement,
      /* 22 */ $.create_statement,
      /* 22 */ $.delete_statement,
      /* 22 */ $.release_statement,
      /* 20 */ $.expression_statement,
      /* 20 */ $.input_clear_statement,
      /* 20 */ $.leave_statement,
      /* 20 */ $.load_picture_statement,
      /* 20 */ $.next_statement,
      /* 20 */ $.os_append_statement,
      /* 20 */ $.os_copy_statement,
      /* 20 */ $.os_rename_statement,
      /* 20 */ $.page_statement,
      /* 20 */ $.show_stats_statement,
      /* 15 */ $.os_create_dir_statement,
      /* 15 */ $.process_events_statement,
      /* 15 */ $.super_statement,
      /* 15 */ $.terminal_statement,
      /* 10 */ $.bell_statement,
      /* 10 */ $.dictionary_statement,
      /* 10 */ $.quit_statement,
      /* 10 */ $.stop_statement,

      // TODO: statements that are hard to integrate due to state explosion or bugs
      // /* 60000 */ $.system_dialog_get_file_statement,
      //
      // These are not expensive but it's all or none at this point
      // /* 1200 */ $.system_dialog_font_statement,
      // /* 400 */ $.system_dialog_printer_setup_statement,
      // /* 300 */ $.system_dialog_get_dir_statement,
      // /* 100 */ $.system_dialog_color_statement,
    ),
});
