// OpenEdge keyword spellings used by labels. A :n suffix gives the minimum
// abbreviation length; standalone short aliases remain separate entries.
// Block labels exclude KEYWORD entries; EDITING labels exclude KEYWORD-ALL.
export const RESERVED_KEYWORDS = `
ACCUMULATE:5 ACTIVE-FORM ACTIVE-WINDOW ADD ALIAS ALL ALTER AMBIGUOUS:5 ANALYZE:6 AND ANY APPLY
ASCENDING:2 ASSIGN ASYNCHRONOUS AT ATTR-SPACE:4 AUDIT-CONTROL AUDIT-POLICY AUTHORIZATION
AUTO-RETURN:8 AVAILABLE:5 BACKGROUND:4 BEFORE-HIDE:8 BEGINS BELL BETWEEN BIG-ENDIAN BLANK BREAK
BUFFER-COMPARE:11 BUFFER-COPY BY BY-POINTER BY-VARIANT-POINTER:16 CALL CAN-DO CAN-FIND CASE
CASE-SENSITIVE:8 CAST CENTERED:6 CHECK CHR CLEAR CLIPBOARD CODEBASE-LOCATOR COL COLON COLOR
COLUMN-LABEL:10 COLUMNS:6 COM-SELF COMPILER CONNECTED CONTROL COPY-LOB COUNT-OF CPSTREAM CREATE
CURRENT CURRENT-CHANGED CURRENT-LANGUAGE:12 CURRENT-WINDOW CURRENT_DATE CURSOR:4 DATABASE
DATASERVERS DATASET DATASET-HANDLE DBCODEPAGE DBCOLLATION DBNAME DBPARAM DBRESTRICTIONS:6
DBTASKID DBTYPE DBVERSION:6 DDE DEBLANK DEBUG-LIST DEBUGGER DECIMALS DECLARE DEFAULT
DEFAULT-WINDOW DEFINE:3 DELETE DELIMITER DESCENDING:4 DICTIONARY:4 DISABLE DISCONNECT:6
DISPLAY:4 DISTINCT DOS:2 DOWN DROP DSLOG-MANAGER DYNAMIC-ENUM DYNAMIC-FUNCTION:12 DYNAMIC-INVOKE
DYNAMIC-NEW DYNAMIC-PROPERTY EACH EDITING ELSE ENABLE ENCODE END ENTRY ERROR-STATUS:10 ESCAPE
ETIME EVENT-PROCEDURE EXCEPT EXCLUSIVE EXCLUSIVE-LOCK:11 EXCLUSIVE-WEB-USER:13 EXISTS EXPORT
FALSE FETCH FIELDS:5 FILE-INFO FILL FIND FIND-CASE-SENSITIVE FIND-GLOBAL FIND-NEXT-OCCURRENCE
FIND-PREV-OCCURRENCE FIND-SELECT FIND-WRAP-AROUND FIRST FIRST-OF FOCUS FONT FORMAT:3 FRAME-COL
FRAME-DB FRAME-DOWN FRAME-FIELD FRAME-FILE FRAME-INDEX:10 FRAME-LINE FRAME-NAME FRAME-ROW
FRAME-VALUE:9 FRAME:4 FROM FROM-CHARS:6 FROM-PIXELS:6 FUNCTION-CALL-TYPE GATEWAYS:7
GET-ATTR-CALL-TYPE GET-BYTE GET-CODEPAGES:12 GET-COLLATIONS:8 GET-ERROR-COLUMN GET-ERROR-ROW
GET-FILE-NAME GET-FILE-OFFSET:14 GET-KEY-VALUE:11 GETBYTE GLOBAL GO-ON GO-PENDING:7 GRANT
GRAPHIC-EDGE:9 GROUP HAVING HEADER HELP HIDE HOST-BYTE-ORDER IF IMPORT IN INDEX INDICATOR INPUT
INPUT-OUTPUT:7 INSERT INTO IS IS-ATTR-SPACE:7 JOIN KBLABEL KEY-CODE KEY-FUNCTION:8 KEY-LABEL
KEYCODE KEYFUNCTION:7 KEYLABEL KEYS KEYWORD LABEL LAST LAST-EVENT:9 LAST-KEY LAST-OF LASTKEY
LDBNAME LEAVE LIBRARY LIKE LIKE-SEQUENTIAL LINE-COUNTER:10 LISTING:5 LITTLE-ENDIAN LOCKED
LOG-MANAGER LOOKUP MAP MEMBER MESSAGE MESSAGE-LINES MOUSE MPE NEW NEXT NEXT-PROMPT NO-ATTR
NO-ATTR-SPACE:9 NO-ERROR NO-FILL:4 NO-HELP NO-HIDE NO-LABELS:8 NO-LOBS NO-LOCK NO-MAP
NO-MESSAGE:6 NO-PAUSE NO-PREFETCH:8 NO-UNDO NO-VALIDATE:6 NO-WAIT NOT:2 NOW:2 NULL NUM-ALIASES:7
NUM-DBS NUM-ENTRIES OFF:2 OLD ON OPEN OPSYS OPTION OR OS-APPEND OS-COMMAND OS-COPY OS-CREATE-DIR
OS-DELETE OS-DIR OS-DRIVES:8 OS-ERROR OS-RENAME OTHERWISE OUTPUT OVERLAY PAGE PAGE-BOTTOM:8
PAGE-NUMBER:8 PAGE-TOP PARAMETER:5 PASSWORD-FIELD PAUSE PDBNAME PERSISTENT:7 PIXELS PREPROCESS:7
PRIVILEGES PROC-HANDLE:7 PROC-STATUS:7 PROCEDURE-CALL-TYPE PROCESS PROFILER PROGRAM-NAME
PROGRESS PROMPT PROMPT-FOR:8 PROMSGS PROPATH PROVERSION:7 PUBLISH PUT PUT-BYTE PUT-KEY-VALUE:11
PUTBYTE QUERY QUERY-TUNING QUIT R-INDEX RCODE-INFORMATION:10 READ-AVAILABLE READ-EXACT-NUM
READKEY RECID RECORD-LENGTH:10 RECTANGLE:4 RELEASE REPEAT REPOSITION RETAIN RETRY RETURN
RETURN-VALUE:10 REVERT REVOKE RUN SAVE SAX-COMPLETE:10 SAX-PARSER-ERROR SAX-RUNNING
SAX-UNINITIALIZED SAX-WRITE-BEGIN SAX-WRITE-COMPLETE SAX-WRITE-CONTENT SAX-WRITE-ELEMENT
SAX-WRITE-ERROR SAX-WRITE-IDLE SAX-WRITE-TAG SCHEMA SCREEN SCREEN-IO SCREEN-LINES SCROLL SDBNAME
SEARCH SEARCH-SELF SECURITY-POLICY SEEK SELECT SELF SESSION SET SET-ATTR-CALL-TYPE SETUSERID:7
SHARE-LOCK:5 SHARED:5 SHOW-STATS:9 SINGLE-RUN SKIP SKIP-GROUP-DUPLICATES SOME SOURCE-PROCEDURE
SPACE STATUS STOP-AFTER STREAM STREAM-HANDLE STREAM-IO STRING-XREF SUBSCRIBE SUPER SYSTEM-DIALOG
TABLE TABLE-HANDLE TARGET-PROCEDURE TENANT-WHERE TERM TERMINAL TEXT TEXT-CURSOR TEXT-SEG-GROW:8
THEN THIS-OBJECT THIS-PROCEDURE TIME TITLE TO TODAY TOP-ONLY TRANS TRANSACTION:8 TRIGGERS:7 TRIM
TRUE UNDERLINE:6 UNDO UNFORMATTED:6 UNION UNIQUE UNIX UNLESS-HIDDEN UNSUBSCRIBE UP UPDATE
USE-INDEX USE-REVVIDEO USE-UNDERLINE USER USERID USING V6FRAME VALUES:5 VIEW VIEW-AS WAIT-FOR
WEB-CONTEXT:7 WHEN WHERE WHILE WINDOW WINDOW-MAXIMIZED:12 WINDOW-MINIMIZED:12 WINDOW-NORMAL WITH
WORK-TABLE:8 WORKFILE WRITE XCODE XREF XREF-XML YES
`;

export const UNRESERVED_KEYWORDS = `
ABSOLUTE:3 ABSTRACT ACCELERATOR ACTIVE ADD-BUFFER ADD-CALC-COLUMN:12 ADD-COLUMNS-FROM
ADD-EVENTS-PROCEDURE:15 ADD-FIELDS-FROM ADD-FIRST ADD-INDEX-FIELD ADD-LAST ADD-LIKE-COLUMN:12
ADD-LIKE-FIELD ADD-LIKE-INDEX ADD-NEW-FIELD ADD-NEW-INDEX ADD-SCHEMA-LOCATION
ADD-SUPER-PROCEDURE:14 ADM-DATA ADVISE ALERT-BOX ALLOW-COLUMN-SEARCHING ALLOW-REPLICATION
ALTERNATE-KEY ALWAYS-ON-TOP ANSI-ONLY ANYWHERE APPEND APPL-ALERT-BOXES:10 APPL-CONTEXT-ID
APPLICATION APPSERVER-INFO APPSERVER-PASSWORD APPSERVER-USERID ARRAY-MESSAGE:7 ASK-OVERWRITE
ASSEMBLY ASYNC-REQUEST-COUNT ASYNC-REQUEST-HANDLE ATTACH ATTACHED-PAIRLIST AUDIT-ENABLED
AUDIT-EVENT-CONTEXT AUTHENTICATION-FAILED AUTO-COMPLETION:9 AUTO-END-KEY AUTO-ENDKEY AUTO-GO
AUTO-INDENT:8 AUTO-RESIZE AUTO-SYNCHRONIZE AUTO-ZAP:6 AUTOMATIC AVAILABLE-FORMATS AVERAGE:3 AVG
BACKWARDS:8 BASE-ADE BASE-KEY BASE64 BASE64-DECODE BASE64-ENCODE BATCH BATCH-MODE BATCH-SIZE
BEFORE-TABLE BEGIN-EVENT-GROUP BGCOLOR:3 BINARY BIND BIND-WHERE BLOB BLOCK-ITERATION-DISPLAY
BLOCK-LEVEL:9 BORDER-BOTTOM-CHARS:15 BORDER-BOTTOM-PIXELS:15 BORDER-BOTTOM:8
BORDER-LEFT-CHARS:13 BORDER-LEFT-PIXELS:13 BORDER-LEFT:8 BORDER-RIGHT-CHARS:14
BORDER-RIGHT-PIXELS:14 BORDER-RIGHT:8 BORDER-TOP-CHARS:12 BORDER-TOP-PIXELS:12 BORDER-TOP:8 BOTH
BOTTOM BOX BOX-SELECTABLE:10 BROWSE BUFFER BUFFER-CHARS BUFFER-CREATE BUFFER-DELETE BUFFER-FIELD
BUFFER-HANDLE BUFFER-LINES BUFFER-NAME:8 BUFFER-PARTITION-ID BUFFER-RELEASE:13 BUFFER-VALUE
BUTTONS:6 BY-REFERENCE BY-VALUE BYTE CACHE CACHE-SIZE CALL-NAME CALL-TYPE CAN-CREATE:8
CAN-DELETE:8 CAN-DO-DOMAIN-SUPPORT CAN-QUERY CAN-READ CAN-SET CAN-WRITE:8 CANCEL-BREAK
CANCEL-BUTTON CAPS CAREFUL-PAINT CATCH CDECL CHAINED CHARACTER:4 CHARACTER_LENGTH CHARSET
CHECKED CHOOSE CLASS CLASS-TYPE CLEAR-APPL-CONTEXT CLEAR-LOG CLEAR-SELECTION:12
CLEAR-SORT-ARROWS:16 CLIENT-CONNECTION-ID CLIENT-PRINCIPAL CLIENT-TTY CLIENT-TYPE
CLIENT-WORKSTATION CLOB CLOSE CLOSE-LOG CODE CODEPAGE CODEPAGE-CONVERT COL-OF COLLATE
COLON-ALIGNED:11 COLOR-TABLE COLUMN-BGCOLOR:10 COLUMN-CODEPAGE COLUMN-DCOLOR COLUMN-FGCOLOR:10
COLUMN-FONT COLUMN-MOVABLE COLUMN-OF COLUMN-PFCOLOR:10 COLUMN-READ-ONLY COLUMN-RESIZABLE
COLUMN-SCROLLING:9 COM-HANDLE COMBO-BOX COMMAND COMPARES:7 COMPILE COMPLETE CONFIG-NAME CONNECT
CONSTRUCTOR CONTAINS CONTENTS CONTEXT CONTEXT-HELP CONTEXT-HELP-FILE CONTEXT-HELP-ID
CONTEXT-POPUP:11 CONTROL-BOX CONTROL-FRAME:12 CONVERT CONVERT-3D-COLORS:10 CONVERT-TO-OFFSET:15
COPY-DATASET COPY-SAX-ATTRIBUTES COPY-TEMP-TABLE COUNT CPCASE CPCOLL CPINTERNAL:5 CPLOG CPPRINT
CPRCODEIN CPRCODEOUT CPTERM CRC-VALUE:7 CREATE-LIKE CREATE-LIKE-SEQUENTIAL CREATE-NODE
CREATE-NODE-NAMESPACE CREATE-RESULT-LIST-ENTRY CREATE-TEST-FILE CURRENT-COLUMN
CURRENT-ENVIRONMENT:11 CURRENT-ITERATION CURRENT-QUERY CURRENT-REQUEST-INFO
CURRENT-RESPONSE-INFO CURRENT-RESULT-ROW CURRENT-ROW-MODIFIED CURRENT-VALUE CURSOR-CHAR
CURSOR-LINE CURSOR-OFFSET DATA-BIND:6 DATA-ENTRY-RETURN:14 DATA-RELATION:8 DATA-SOURCE
DATA-SOURCE-COMPLETE-MAP DATA-SOURCE-MODIFIED DATA-SOURCE-ROWID DATA-TYPE:6 DATE DATE-FORMAT:6
DATETIME DATETIME-TZ DAY DB-CONTEXT DB-REFERENCES DCOLOR DDE-ERROR DDE-ID:5 DDE-ITEM DDE-NAME
DDE-TOPIC DEBUG-ALERT DEBUG:4 DECIMAL:3 DECLARE-NAMESPACE DECRYPT DEFAULT-BUFFER-HANDLE
DEFAULT-BUTTON:11 DEFAULT-COMMIT DEFAULT-EXTENSION:10 DEFAULT-VALUE DEFINE-USER-EVENT-MANAGER
DEFINED DELEGATE DELETE-CHAR DELETE-CURRENT-ROW DELETE-LINE DELETE-RESULT-LIST-ENTRY
DELETE-SELECTED-ROWS:19 DESELECT-FOCUSED-ROW DESELECT-ROWS DESELECT-SELECTED-ROW DESTRUCTOR
DIALOG-BOX DIR DISABLE-AUTO-ZAP DISABLE-DUMP-TRIGGERS DISABLE-LOAD-TRIGGERS DISABLED
DISPLAY-MESSAGE DISPLAY-TYPE:9 DOMAIN-DESCRIPTION DOMAIN-NAME DOMAIN-TYPE DOUBLE DRAG-ENABLED
DROP-DOWN DROP-DOWN-LIST DROP-TARGET DUMP DYNAMIC DYNAMIC-CURRENT-VALUE ECHO EDGE EDGE-CHARS:6
EDGE-PIXELS:6 EDIT-CAN-PASTE EDIT-CAN-UNDO EDIT-CLEAR EDIT-COPY EDIT-CUT EDIT-PASTE EDIT-UNDO
EDITOR EMPTY EMPTY-TEMP-TABLE ENABLED ENCRYPT ENCRYPT-AUDIT-MAC-KEY ENCRYPTION-SALT END-DOCUMENT
END-ELEMENT END-EVENT-GROUP END-FILE-DROP END-KEY END-USER-PROMPT ENDKEY ENTERED
ENTITY-EXPANSION-LIMIT ENUM EQ ERROR ERROR-COLUMN:9 ERROR-OBJECT ERROR-ROW ERROR-STACK-TRACE
EVENT-GROUP-ID EVENT-PROCEDURE-CONTEXT EVENT-TYPE:7 EVENTS:5 EXCLUSIVE-ID EXECUTE EXIT-CODE EXP
EXPAND EXPANDABLE EXPLICIT EXPORT-PRINCIPAL EXTENDED EXTENT EXTERNAL FETCH-SELECTED-ROW
FGCOLOR:3 FILE FILE-CREATE-DATE:13 FILE-CREATE-TIME:13 FILE-MOD-DATE:10 FILE-MOD-TIME:10
FILE-NAME FILE-OFFSET:8 FILE-SIZE FILE-TYPE FILENAME FILL-IN FILLED FILTERS FINAL FINALLY
FIND-BY-ROWID FIND-CURRENT FIND-FIRST FIND-LAST FIND-UNIQUE FINDER FIRST-ASYNC FIRST-CHILD
FIRST-COLUMN FIRST-FORM FIRST-OBJECT FIRST-PROCEDURE:10 FIRST-SERVER:10 FIRST-TAB-ITEM:11
FIT-LAST-COLUMN FIX-CODEPAGE FIXED-ONLY FLAGS FLAT-BUTTON FLOAT FOCUSED-ROW FOCUSED-ROW-SELECTED
FONT-TABLE FORCE-FILE FOREGROUND:4 FOREIGN-KEY-HIDDEN FORM-LONG-INPUT FORMATTED:8 FORWARDS:7
FRAGMENT:7 FRAME-SPACING:9 FRAME-X FRAME-Y FREQUENCY FROM-CURRENT:8 FULL-HEIGHT
FULL-HEIGHT-CHARS:13 FULL-HEIGHT-PIXELS:13 FULL-PATHNAME:10 FULL-WIDTH-CHARS:10
FULL-WIDTH-PIXELS:10 FUNCTION GENERATE-MD5 GENERATE-PBE-KEY GENERATE-PBE-SALT
GENERATE-RANDOM-KEY GENERATE-UUID GET-ATTRIBUTE GET-ATTRIBUTE-NODE GET-BINARY-DATA
GET-BLUE-VALUE:8 GET-BROWSE-COLUMN:14 GET-BUFFER-HANDLE GET-CALLBACK-PROC-CONTEXT
GET-CALLBACK-PROC-NAME GET-CGI-LIST GET-CGI-LONG-VALUE GET-CGI-VALUE GET-CLASS GET-CONFIG-VALUE
GET-CURRENT:8 GET-DIR GET-DOUBLE GET-DROPPED-FILE GET-DYNAMIC GET-FILE GET-FIRST:8 GET-FLOAT
GET-GREEN-VALUE:9 GET-INDEX-BY-NAMESPACE-NAME GET-INDEX-BY-QNAME GET-INT64 GET-ITERATION
GET-LAST GET-LOCALNAME-BY-INDEX GET-LONG GET-MESSAGE GET-NEXT GET-NUMBER GET-POINTER-VALUE
GET-PREV GET-PRINTERS GET-PROPERTY GET-QNAME-BY-INDEX GET-RED-VALUE:7 GET-REPOSITIONED-ROW
GET-RGB-VALUE:7 GET-SELECTED-WIDGET:12 GET-SHORT GET-SIGNATURE GET-SIZE GET-STRING GET-TAB-ITEM
GET-TEXT-HEIGHT GET-TEXT-HEIGHT-CHARS:17 GET-TEXT-HEIGHT-PIXELS:17 GET-TEXT-WIDTH
GET-TEXT-WIDTH-CHARS:16 GET-TEXT-WIDTH-PIXELS:16 GET-TYPE-BY-INDEX GET-TYPE-BY-NAMESPACE-NAME
GET-TYPE-BY-QNAME GET-UNSIGNED-LONG GET-UNSIGNED-SHORT GET-URI-BY-INDEX GET-VALUE-BY-INDEX
GET-VALUE-BY-NAMESPACE-NAME GET-VALUE-BY-QNAME GET-WAIT-STATE:8 GET:2 GRID-FACTOR-HORIZONTAL:13
GRID-FACTOR-VERTICAL:13 GRID-SNAP GRID-UNIT-HEIGHT GRID-UNIT-HEIGHT-CHARS:18
GRID-UNIT-HEIGHT-PIXELS:18 GRID-UNIT-WIDTH GRID-UNIT-WIDTH-CHARS:17 GRID-UNIT-WIDTH-PIXELS:17
GRID-VISIBLE GROUP-BOX GT GUID HANDLER:6 HAS-RECORDS HEIGHT HEIGHT-CHARS:8 HEIGHT-PIXELS:8
HELP-TOPIC HEX-DECODE HEX-ENCODE HIDDEN HORIZONTAL:4 HTML-CHARSET HTML-END-OF-LINE
HTML-END-OF-PAGE HTML-FRAME-BEGIN HTML-FRAME-END HTML-HEADER-BEGIN HTML-HEADER-END
HTML-TITLE-BEGIN HTML-TITLE-END HWND ICON IMAGE IMAGE-DOWN IMAGE-INSENSITIVE IMAGE-SIZE
IMAGE-SIZE-CHARS:12 IMAGE-SIZE-PIXELS:12 IMAGE-UP IMMEDIATE-DISPLAY IMPLEMENTS IMPORT-PRINCIPAL
IN-HANDLE INCREMENT-EXCLUSIVE-ID INDEX-HINT INDEX-INFORMATION:10 INDEXED-REPOSITION
INFORMATION:4 INHERIT-BGCOLOR:11 INHERIT-FGCOLOR:11 INHERITS INIT INITIAL INITIAL-DIR
INITIAL-FILTER INITIALIZE INITIALIZE-DOCUMENT-TYPE INITIATE INNER INNER-CHARS INNER-LINES
INPUT-VALUE INSERT-ATTRIBUTE INSERT-BACKTAB:8 INSERT-FILE INSERT-ROW INSERT-STRING INSERT-TAB:8
INT64 INTEGER:3 INTERFACE INTERNAL-ENTRIES INVOKE IS-CLASS:7 IS-JSON IS-LEAD-BYTE IS-OPEN
IS-PARAMETER-SET IS-PARTITIONED:13 IS-ROW-SELECTED IS-SELECTED IS-XML ITEM ITEMS-PER-ROW
JOIN-BY-SQLDB KEEP-CONNECTION-OPEN KEEP-FRAME-Z-ORDER:12 KEEP-MESSAGES KEEP-SECURITY-CACHE
KEEP-TAB-ORDER KEY KEYCACHE-JOIN KEYWORD-ALL LABEL-BGCOLOR:9 LABEL-DCOLOR:8 LABEL-FGCOLOR:9
LABEL-FONT LABEL-PFCOLOR:9 LABELS LABELS-HAVE-COLONS LANDSCAPE LANGUAGES:8 LARGE LARGE-TO-SMALL
LAST-ASYNC LAST-BATCH LAST-CHILD LAST-FORM LAST-OBJECT LAST-PROCEDURE:10 LAST-SERVER:9
LAST-TAB-ITEM:10 LC LE LEFT LEFT-ALIGNED:10 LEFT-TRIM LENGTH LINE LIST-EVENTS LIST-ITEM-PAIRS
LIST-ITEMS LIST-PROPERTY-NAMES LIST-QUERY-ATTRS LIST-SET-ATTRS LIST-WIDGETS LITERAL-QUESTION
LOAD LOAD-DOMAINS LOAD-ICON LOAD-IMAGE LOAD-IMAGE-DOWN LOAD-IMAGE-INSENSITIVE LOAD-IMAGE-UP
LOAD-MOUSE-POINTER:12 LOAD-PICTURE LOAD-RESULT-INTO LOAD-SMALL-ICON LOB-DIR LOCAL-NAME
LOCAL-VERSION-INFO LOCATOR-COLUMN-NUMBER LOCATOR-LINE-NUMBER LOCATOR-PUBLIC-ID LOCATOR-SYSTEM-ID
LOCATOR-TYPE LOCK-REGISTRATION LOG LOG-AUDIT-EVENT LOGICAL LOGIN-EXPIRATION-TIMESTAMP LOGIN-HOST
LOGIN-STATE LOGOUT LONG LONGCHAR:6 LOOKAHEAD LT MANDATORY MANUAL-HIGHLIGHT MARGIN-EXTRA
MARGIN-HEIGHT MARGIN-HEIGHT-CHARS:15 MARGIN-HEIGHT-PIXELS:15 MARGIN-WIDTH MARGIN-WIDTH-CHARS:14
MARGIN-WIDTH-PIXELS:14 MARK-NEW MARK-ROW-STATE MATCHES MAX MAX-BUTTON MAX-CHARS MAX-DATA-GUESS
MAX-HEIGHT MAX-HEIGHT-CHARS:12 MAX-HEIGHT-PIXELS:12 MAX-ROWS MAX-SIZE MAX-VALUE:7 MAX-WIDTH
MAX-WIDTH-CHARS:11 MAX-WIDTH-PIXELS:11 MAXIMIZE MAXIMUM MAXIMUM-LEVEL MD5-DIGEST MEMPTR
MEMPTR-TO-NODE-VALUE MENU MENU-BAR MENU-ITEM MENU-KEY:6 MENU-MOUSE:6 MENUBAR MERGE-BY-FIELD
MESSAGE-AREA MESSAGE-AREA-FONT MESSAGE-LINE METHOD MIN-BUTTON MIN-COLUMN-WIDTH-CHARS:18
MIN-COLUMN-WIDTH-PIXELS:18 MIN-HEIGHT MIN-HEIGHT-CHARS:12 MIN-HEIGHT-PIXELS:12 MIN-SIZE
MIN-VALUE:7 MIN-WIDTH MIN-WIDTH-CHARS:11 MIN-WIDTH-PIXELS:11 MINIMUM:3 MOD MODIFIED MODULO MONTH
MOUSE-POINTER:7 MOVABLE MOVE-AFTER-TAB-ITEM:10 MOVE-BEFORE-TAB-ITEM:10 MOVE-COLUMN:8
MOVE-TO-BOTTOM:9 MOVE-TO-EOF MOVE-TO-TOP:9 MTIME MULTI-COMPILE MULTIPLE MULTIPLE-KEY
MULTITASKING-INTERVAL MUST-EXIST NAME NAMESPACE-PREFIX NAMESPACE-URI NATIVE NE
NEEDS-APPSERVER-PROMPT NEEDS-PROMPT NESTED NEW-INSTANCE NEW-ROW NEXT-COLUMN:8 NEXT-ROWID
NEXT-SIBLING NEXT-TAB-ITEM:12 NEXT-VALUE NO-APPLY NO-ARRAY-MESSAGE:10 NO-ASSIGN NO-ATTR-LIST:9
NO-AUTO-VALIDATE NO-BIND-WHERE NO-BOX NO-COLUMN-SCROLLING:12 NO-CONSOLE NO-CONVERT
NO-CONVERT-3D-COLORS:13 NO-CURRENT-VALUE NO-DEBUG NO-DRAG NO-ECHO NO-EMPTY-SPACE NO-FOCUS
NO-INDEX-HINT NO-INHERIT-BGCOLOR:14 NO-INHERIT-FGCOLOR:14 NO-JOIN-BY-SQLDB NO-KEYCACHE-JOIN
NO-LOOKAHEAD NO-ROW-MARKERS NO-SCROLLBAR-VERTICAL:14 NO-SEPARATE-CONNECTION NO-SEPARATORS
NO-TAB-STOP:6 NO-UNDERLINE:6 NO-WORD-WRAP NODE-VALUE NODE-VALUE-TO-MEMPTR NON-SERIALIZABLE
NONAMESPACE-SCHEMA-LOCATION NONE NORMALIZE NOT-ACTIVE NUM-BUFFERS NUM-BUTTONS:7 NUM-COLUMNS:7
NUM-COPIES NUM-DROPPED-FILES NUM-FIELDS NUM-FORMATS NUM-ITEMS NUM-ITERATIONS NUM-LINES
NUM-LOCKED-COLUMNS:14 NUM-MESSAGES NUM-PARAMETERS NUM-REFERENCES NUM-REPLACED:8 NUM-RESULTS
NUM-SELECTED NUM-SELECTED-ROWS NUM-SELECTED-WIDGETS NUM-TABS NUM-TO-RETAIN
NUM-VISIBLE-COLUMNS:15 NUMERIC NUMERIC-FORMAT:9 OBJECT OK OK-CANCEL ON-FRAME-BORDER:8 OPTIONS
OPTIONS-FILE ORDERED-JOIN ORDINAL OS-GETENV OUTER OUTER-JOIN OVERRIDE OWNER PAGE-SIZE
PAGE-WIDTH:8 PAGED PARENT PARENT-FIELDS-AFTER PARENT-FIELDS-BEFORE PARENT-ID-FIELD
PARENT-ID-RELATION PARSE-STATUS PARTIAL-KEY PASCAL PATHNAME PBE-HASH-ALGORITHM:12 PBE-KEY-ROUNDS
PERFORMANCE:4 PERSISTENT-CACHE-DISABLED PFCOLOR:3 PIXELS-PER-COLUMN:14 PIXELS-PER-ROW
POPUP-MENU:7 POPUP-ONLY:7 PORTRAIT POSITION PRECISION PREFER-DATASET PREPARE-STRING PREPARED
PRESELECT:6 PREV PREV-COLUMN:8 PREV-SIBLING PREV-TAB-ITEM:10 PRIMARY PRINTER
PRINTER-CONTROL-HANDLE PRINTER-HDC PRINTER-NAME PRINTER-PORT PRINTER-SETUP PRIVATE
PRIVATE-DATA:9 PROCEDURE-TYPE PROCEDURE:5 PROGRESS-SOURCE:10 PROPERTY PROTECTED PROXY
PROXY-PASSWORD PROXY-USERID PUBLIC PUBLIC-ID PUBLISHED-EVENTS PUT-BITS PUT-BYTES PUT-DOUBLE
PUT-FLOAT PUT-INT64 PUT-LONG PUT-SHORT PUT-STRING PUT-UNSIGNED-LONG PUT-UNSIGNED-SHORT
QUERY-CLOSE QUERY-OFF-END QUERY-OPEN QUERY-PREPARE QUESTION QUOTER RADIO-BUTTONS RADIO-SET
RANDOM RAW RAW-TRANSFER READ READ-FILE READ-JSON READ-ONLY READ-XML REAL RECURSIVE
REFERENCE-ONLY REFRESH REFRESH-AUDIT-POLICY REFRESHABLE REGISTER-DOMAIN RELATION-FIELDS:11
REMOTE REMOVE-EVENTS-PROCEDURE:18 REMOVE-SUPER-PROCEDURE:17 REPLACE REPLACE-SELECTION-TEXT
REPOSITION-BACKWARD:15 REPOSITION-FORWARD:15 REPOSITION-TO-ROW REPOSITION-TO-ROWID REQUEST
REQUEST-INFO RESET RESIZABLE:6 RESIZE RESPONSE-INFO RESTART-ROW RESTART-ROWID RESULT
RETAIN-SHAPE:8 RETRY-CANCEL RETURN-INSERTED:10 RETURN-TO-START-DIR:18 RETURN-VALUE-DATA-TYPE
RETURNS REVERSE-FROM RGB-VALUE:5 RIGHT RIGHT-ALIGNED:11 RIGHT-TRIM ROLES:4 ROUND ROUNDED
ROUTINE-LEVEL ROW ROW-HEIGHT ROW-HEIGHT-CHARS:12 ROW-HEIGHT-PIXELS:12 ROW-MARKERS:6 ROW-OF
ROW-RESIZABLE ROWID RULE RUN-PROCEDURE:8 SAVE-AS SAVE-FILE SAX-ATTRIBUTES SAX-PARSE
SAX-PARSE-FIRST SAX-PARSE-NEXT SAX-READER SAX-WRITER SCHEMA-LOCATION SCHEMA-MARSHAL SCHEMA-PATH
SCREEN-VALUE:10 SCROLL-BARS SCROLL-DELTA SCROLL-OFFSET SCROLL-TO-CURRENT-ROW SCROLL-TO-ITEM:11
SCROLL-TO-SELECTED-ROW SCROLLABLE SCROLLBAR-HORIZONTAL:11 SCROLLBAR-VERTICAL:11
SCROLLED-ROW-POSITION:16 SCROLLING SEAL SEAL-TIMESTAMP SECTION SELECT-ALL SELECT-FOCUSED-ROW
SELECT-NEXT-ROW SELECT-PREV-ROW SELECT-ROW SELECTABLE SELECTED SELECTION-END SELECTION-LIST
SELECTION-START SELECTION-TEXT SEND SENSITIVE SEPARATE-CONNECTION SEPARATOR-FGCOLOR:13
SEPARATORS SERIALIZABLE SERIALIZE-HIDDEN SERIALIZE-NAME SERVER
SERVER-CONNECTION-BOUND-REQUEST:26 SERVER-CONNECTION-BOUND:20 SERVER-CONNECTION-CONTEXT:20
SERVER-CONNECTION-ID SERVER-OPERATING-MODE SERVER-SOCKET SESSION-ID SET-APPL-CONTEXT
SET-ATTRIBUTE SET-ATTRIBUTE-NODE SET-BLUE-VALUE:8 SET-BREAK SET-BUFFERS SET-BYTE-ORDER
SET-CALLBACK SET-CLIENT SET-COMMIT SET-CONTENTS SET-DB-CLIENT SET-DYNAMIC SET-GREEN-VALUE:9
SET-INPUT-SOURCE SET-OPTION SET-OUTPUT-DESTINATION SET-PARAMETER SET-POINTER-VALUE:15
SET-PROPERTY SET-RED-VALUE:7 SET-REPOSITIONED-ROW SET-RGB-VALUE:7 SET-ROLLBACK SET-SELECTION
SET-SIZE SET-SORT-ARROW SET-WAIT-STATE:8 SHA1-DIGEST SHOW-IN-TASKBAR:12 SIDE-LABEL-HANDLE:12
SIDE-LABELS:8 SIGNATURE SILENT SIMPLE SINGLE SINGLETON SIZE SIZE-CHARS:6 SIZE-PIXELS:6
SKIP-DELETED-RECORD:16 SLIDER SMALL-ICON SMALL-TITLE SMALLINT SOAP-HEADER SOAP-HEADER-ENTRYREF
SOCKET SORT SORT-ASCENDING SORT-NUMBER SOURCE SQL SQRT SSL-SERVER-NAME STANDALONE START
START-DOCUMENT START-ELEMENT STARTING STATE-DETAIL STATIC STATUS-AREA STATUS-AREA-FONT STDCALL
STOP STOP-OBJECT STOP-PARSING STOPPED:6 STORED-PROCEDURE:11 STRETCH-TO-FIT STRICT
STRICT-ENTITY-RESOLUTION STRING STRING-VALUE SUB-AVERAGE:7 SUB-COUNT SUB-MAXIMUM:7 SUB-MENU
SUB-MENU-HELP SUB-MINIMUM:7 SUB-TOTAL SUBSTITUTE:5 SUBSTRING:5 SUBTYPE SUM SUPER-PROCEDURES:10
SUPPRESS-NAMESPACE-PROCESSING SUPPRESS-WARNINGS:10 SYMMETRIC-ENCRYPTION-ALGORITHM
SYMMETRIC-ENCRYPTION-IV SYMMETRIC-ENCRYPTION-KEY SYMMETRIC-SUPPORT SYSTEM-ALERT-BOXES:12
SYSTEM-HELP SYSTEM-ID TAB-POSITION TAB-STOP TABLE-NUMBER:9 TABLE-SCAN TARGET TEMP-DIRECTORY:8
TEMP-TABLE TEMP-TABLE-PREPARE:17 TENANT TERMINATE TEXT-SELECTED THREAD-SAFE THREE-D THROUGH
THROW THRU TIC-MARKS TIME-SOURCE TITLE-BGCOLOR:9 TITLE-DCOLOR:8 TITLE-FGCOLOR:9 TITLE-FONT:8
TO-ROWID TOGGLE-BOX TOOLTIPS:7 TOP TOP-NAV-QUERY TOPIC TOTAL TRAILING TRANS-INIT-PROCEDURE:15
TRANSACTION-MODE TRANSPARENT:8 TRUNCATE:5 TTCODEPAGE TYPE TYPE-OF UNBOX UNBUFFERED:6 UNIQUE-ID
UNIQUE-MATCH UNLOAD UNSIGNED-LONG UPDATE-ATTRIBUTE URL URL-DECODE URL-ENCODE URL-PASSWORD
URL-USERID USE USE-DICT-EXPS:7 USE-FILENAME USE-TEXT USE-WIDGET-POOL USER-ID V6DISPLAY
VALID-EVENT VALID-HANDLE VALID-OBJECT VALIDATE VALIDATE-EXPRESSION:18 VALIDATE-MESSAGE
VALIDATE-SEAL VALIDATION-ENABLED VARIABLE:3 VERBOSE:4 VERSION VERTICAL:4
VIEW-FIRST-COLUMN-ON-REOPEN VIRTUAL-HEIGHT VIRTUAL-HEIGHT-CHARS:16 VIRTUAL-HEIGHT-PIXELS:16
VIRTUAL-WIDTH VIRTUAL-WIDTH-CHARS:15 VIRTUAL-WIDTH-PIXELS:15 VISIBLE VOID WAIT WARNING WEEKDAY
WIDGET WIDGET-ENTER:8 WIDGET-HANDLE:8 WIDGET-ID WIDGET-LEAVE:8 WIDGET-POOL WIDTH WIDTH-CHARS:7
WIDTH-PIXELS:7 WINDOW-NAME WINDOW-STATE:10 WINDOW-SYSTEM:10 WORD-INDEX WORD-WRAP
WORK-AREA-HEIGHT-PIXELS:18 WORK-AREA-WIDTH-PIXELS:17 WORK-AREA-X WORK-AREA-Y WRITE-CDATA
WRITE-CHARACTERS WRITE-COMMENT WRITE-DATA WRITE-DATA-ELEMENT WRITE-EMPTY-ELEMENT
WRITE-ENTITY-REF WRITE-EXTERNAL-DTD WRITE-FRAGMENT WRITE-JSON WRITE-MESSAGE
WRITE-PROCESSING-INSTRUCTION WRITE-STATUS WRITE-XML WRITE-XMLSCHEMA X X-DOCUMENT X-NODEREF X-OF
XML-DATA-TYPE XML-ENTITY-EXPANSION-LIMIT XML-NODE-NAME XML-NODE-TYPE XML-SCHEMA-PATH:14
XML-STRICT-ENTITY-RESOLUTION XML-SUPPRESS-NAMESPACE-PROCESSING Y Y-OF YEAR YEAR-OFFSET YES-NO
YES-NO-CANCEL
`;
